# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- feat/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: ls -a
  displayName: 'Where am I ?'

- script: |
    npm install
    npm run build
  workingDirectory: goal-keeper
  displayName: 'npm install and build'

- task: CopyFiles@2
  displayName: 'Copy the build files to $(Build.ArtifactStagingDirectory)'
  workingDirectory: goal-keeper
  inputs:
    Contents: 'build/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- script: ls -a
  displayName: 'Where am I now?'
  workingDirectory: goal-keeper

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: succeeded()
  inputs: 
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: 'www'
