trigger: 
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: BuildAndPush
    displayName: 'Build & Push to ACR'
    steps:
      - script: echo "Build & Push to ACR"
        displayName: 'Build & Push to ACR'
