parameters:
  - name: buildConfiguration
    displayName: buildConfiguration
    type: string
    default: release

steps:
  # - script: |
  #     echo ${{ parameters.buildConfiguration }}
  #     ls -a
  #   displayName: 'Services azure-pipelines'
  - task: UseDotNet@2
    inputs:
      version: '5.0.x'

  - template: ./dotnet-build.yml