INSERT INTO Stats.Teams
([Name], CreatedOn, CreatedBy, ModifiedOn, ModifiedBy)
VALUES
  ('Royal Antwerp FC', GETDATE(), 'Seed', GETDATE(), 'Seed')
, ('Club Brugge', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('KAA Gent', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('Cercle Brugge', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('Beerschot VA', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('Standard Luik', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('Oud-Heverlee Leuven', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('KV Kortrijk', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('Royal Charleroi Sporting Club', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('KV Mechelen', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('KV Oostende', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('RSC Anderlecht', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('Royal Excel Moeskroen', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('KRC Genk', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('Sint-Truidense VV', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('KVRS Waasland - SK Beveren', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('KAS Eupen', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('SV Zulte Waregem', GETDATE(), 'Seed', GETDATE(), 'Seed') 