INSERT INTO dbo.Countries
([TwoLetterISOCode], [Name], CreatedUtc, CreatedBy, ModifiedUtc, ModifiedBy)
VALUES
  ('AL', 'Albania'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('DZ', 'Algeria'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('AO', 'Angola'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('AR', 'Argentina'								, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('AU', 'Australia'								, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('AT', 'Austria'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('BE', 'Belgium'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('BJ', 'Benin'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('BA', 'Bosnia and Herzegovina'					, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('BR', 'Brazil'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('BG', 'Bulgaria'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('BF', 'Burkina Faso'								, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('BI', 'Burundi'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('CM', 'Cameroon'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('CA', 'Canada'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('CV', 'Cape Verde'								, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('TD', 'Chad'										, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('CO', 'Colombia'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('KM', 'Comoros'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('CG', 'Congo'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('CR', 'Costa Rica'								, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('CI', 'Côte D''Ivoire'							, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('HR', 'Croatia'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('CY', 'Cyprus'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('CZ', 'Czech Republic'							, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('DK', 'Denmark'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('FI', 'Finland'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('FR', 'France'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('GM', 'Gambia'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('GE', 'Georgia'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('DE', 'Germany'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('GH', 'Ghana'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('GR', 'Greece'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('GN', 'Guinea'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('GW', 'Guinea-Bissau'							, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('HT', 'Haiti'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('HU', 'Hungary'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('IS', 'Iceland'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('IE', 'Ireland'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('IR', 'Islamic Republic of Iran'					, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('IL', 'Israel'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('IT', 'Italy'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('JM', 'Jamaica'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('JP', 'Japan'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('JO', 'Jordan'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('KZ', 'Kazakhstan'								, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('KE', 'Kenya'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('KR', 'Republic of Korea'						, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('LU', 'Luxembourg'								, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('MK', 'the Former Yugoslav Republic Of Macedonia', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('MY', 'Malaysia'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('ML', 'Mali'										, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('MT', 'Malta'										, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('MX', 'Mexico'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('MD', 'Republic of Moldova'						, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('ME', 'Montenegro'								, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('MA', 'Morocco'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('NL', 'Netherlands'								, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('NZ', 'New Zealand'								, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('NG', 'Nigeria'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('NO', 'Norway'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('PA', 'Panama'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('PE', 'Peru'										, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('PL', 'Poland'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('PT', 'Portugal'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('RO', 'Romania'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('RW', 'Rwanda'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('SN', 'Senegal'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('RS', 'Serbia'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('SL', 'Sierra Leone'								, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('SK', 'Slovakia'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('SI', 'Slovenia'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('ES', 'Spain'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('SR', 'Suriname'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('SE', 'Sweden'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('CH', 'Switzerland'								, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('CD', 'The Democratic Republic Of The Congo'		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('TH', 'Thailand'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('TT', 'Trinidad and Tobago'						, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('TN', 'Tunisia'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('TR', 'Turkey'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('UA', 'Ukraine'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('GB', 'United Kingdom'							, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('US', 'United States'							, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('UY', 'Uruguay'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('VE', 'Bolivarian Republic of Venezuela'			, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('ZM', 'Zambia'									, GETDATE(), 'Seed', GETDATE(), 'Seed'),  
  ('ZW', 'Zimbabwe'									, GETDATE(), 'Seed', GETDATE(), 'Seed')