INSERT INTO Stats.Players
(TeamId, FirstName, LastName, ShirtNumber, Position, CreatedUtc, CreatedBy, ModifiedUtc, ModifiedBy)
VALUES
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%'), 'Lucas', 'Pirard', 21, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%'), 'Kerian', 'Atheba', 26, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%'), 'Tibo', 'Herbots', 33, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%'), 'Anthony', 'Moris', 49, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%'), 'Bart', 'Nieuwkoop', 2, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%'), 'Jonas', 'Bager', 4, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%'), 'Matthew', 'Sorinola', 7, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%'), 'Christian', 'Burgess', 16, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%'), 'Guillaume', 'François', 19, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%'), 'Siebe', 'Van Der Heyden', 44, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%'), 'Ismaël', 'Kandouss', 59, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%'), 'Casper', 'Nielsen', 6, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%'), 'Lazare', 'Amani', 8, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%'), 'Marcel', 'Lewis', 10, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%'), 'Lorenzo', 'Paolucci', 11, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%'), 'Teddy', 'Teuma', 17, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%'), 'Senne', 'Lynen', 20, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%'), 'Ilyes', 'Ziani', 24, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%'), 'Damien', 'Marcq', 25, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%'), 'Deniz', 'Undav', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%'), 'Dante', 'Vanzeir', 13, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%'), 'Perdo', 'Lubamba', 22, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%'), 'Aron', 'Sigurdarson', 23, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%'), 'Felipe', 'Avenatti', 90, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%'), 'Loïc', 'Lapoussin', 94, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),

  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RFC Seraing%'), 'Maxime', 'Mignon', 22, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RFC Seraing%'), 'Guillaume', 'Dietsch', 30, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RFC Seraing%'), 'Timothy', 'Galje', 51, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RFC Seraing%'), 'Benjamin', 'Boulenger', 24, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RFC Seraing%'), 'Wagane', 'Faye', 4, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RFC Seraing%'), 'Yahya', 'Nadrani', 20, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RFC Seraing%'), 'Theo', 'Pierrot', 6, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RFC Seraing%'), 'Francecsco', 'D''Onofrio', 37, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RFC Seraing%'), 'Gaël', 'Kakudji', 25, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RFC Seraing%'), 'Gérald', 'Kilota', 8, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RFC Seraing%'), 'Antoine', 'Bernier', 12, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RFC Seraing%'), 'Mansoni', 'Sambu', 21, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RFC Seraing%'), 'Morgan', 'Poaty', 18, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RFC Seraing%'), 'Abdelhafid', 'Sabri', 10, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RFC Seraing%'), 'Sami', 'Lahssaini', 15, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RFC Seraing%'), 'Serkan', 'Basha', 13, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RFC Seraing%'), 'Ablie', 'Jallow', 36, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RFC Seraing%'), 'Ibrahima', 'Cissé', 44, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RFC Seraing%'), 'Adel', 'Adel Bo', 58, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RFC Seraing%'), 'Rayan', 'Djedje', 38, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RFC Seraing%'), 'Mathieu', 'Cachbach', 17, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RFC Seraing%'), 'Youssef', 'Maziz', 88, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RFC Seraing%'), 'Ali', 'Sanogo', 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RFC Seraing%'), 'Marius', 'Mouandilmadji', 7, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed')
