DECLARE 
	@Anderlecht BIGINT =		(SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'),
	@Antwerp BIGINT =			(SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Antwerp FC%'),
	@Beerschot BIGINT =			(SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'),
	@CercleBrugge BIGINT =		(SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'),
	@ClubBrugge BIGINT =		(SELECT Id FROM Stats.Teams WHERE [Name] like '%Club Brugge%'),
	@Charleroi BIGINT =			(SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'),
	@Eupen BIGINT =				(SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'),
	@Genk BIGINT =				(SELECT Id FROM Stats.Teams WHERE [Name] like '%KRC Genk%'),
	@Gent BIGINT =				(SELECT Id FROM Stats.Teams WHERE [Name] like '%KAA Gent%'),
	@Mechelen BIGINT =			(SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'),
	@Kortrijk BIGINT =			(SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'),
	@OHL BIGINT =				(SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'),
	@Oostende BIGINT =			(SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'),
	@Seraing BIGINT =			(SELECT Id FROM Stats.Teams WHERE [Name] like '%RFC Seraing%'),
	@StandardLuik BIGINT =		(SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'),
	@STVV BIGINT =				(SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'),
	@ZulteWaregem BIGINT =		(SELECT Id FROM Stats.Teams WHERE [Name] like '%Zulte Waregem%'),
	@Union BIGINT =				(SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%'),
	@Moucron BIGINT =			(SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'),
	@WaaslandBeveren BIGINT =	(SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%')

INSERT INTO Stats.Players
(TeamId, FirstName, LastName, ShirtNumber, Position, CreatedUtc, CreatedBy, ModifiedUtc, ModifiedBy)
VALUES
  (@Antwerp, 'Jean', 'Butez', 46, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Davor', 'Matijaš', 71, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Alireza', 'Beiranvand', 1, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Ritchie', 'De Laet', 2, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Abdoulaye', 'Seck', 4, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Aurélio', 'Buta', 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Dragan', 'Lausberg', 64, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Luete Ava', 'Dongo', 12, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Jordan', 'Lukaku', 94, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Jérémy', 'Gelin', 26, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Frank', 'Boya', 15, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Júnior', 'Pius', 40, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Dylan', 'Batubinsika', 21, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Simen', 'Juklerød', 6, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Christian', 'Benavente Bristol', 24, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Birger', 'Verstraete', 5, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Nana', 'Ampomah', 23, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Nill', 'De Pauw', 14, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Manuel', 'Benson', 28, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Koji', 'Miyoshi', 19, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Pieter', 'Gerkens', 16, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Louis', 'Verstraete', 33, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Sander', 'Cooman', 20, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@Antwerp, 'Alexis', 'De Sart', 25, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@Antwerp, 'Lior', 'Refaelov', 11, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Faris', 'Haroun', 38, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Bruny', 'Nsimba', 22, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Guy', 'Mbenza Kamboleke', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@Antwerp, 'Didier', 'Lamkel Ze', 7, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Ivo', 'Rodrigues', 8, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Michael', 'Frey', 99, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Viktor', 'Fischer', 7, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@Antwerp, 'Dieumerci', 'Mbokani', 70, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),


  (@ClubBrugge, 'Ethan', 'Horvath', 22, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Nick', 'Shinton', 33, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Simon', 'Mignolet', 88, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Senne', 'Lammens', 91, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Eduard', 'Sobol', 2, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Odilon', 'Kossounou', 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Matej', 'Mitrovic', 15, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Simon', 'Deli', 17, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Federico', 'Ricca', 18, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Ignace', 'Van Der Brempt', 28, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Brandon', 'Mechele', 44, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Clinton', 'Mata', 77, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Éder', 'Balanta', 3, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Krépin', 'Diatta', 11, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Hans', 'Vanaken', 20, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Ruud', 'Vormer', 25, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Mats', 'Rits', 26, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Tibo', 'Persyn', 16, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Maxim', 'De Cuyper', 55, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Charles', 'De Ketelaere', 90, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Thomas', 'Van Den Keybus', 97, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Amadou', 'Sagna', 7, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Michael', 'krmenčík', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Noa', 'Lang', 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@ClubBrugge, 'Siebe', 'Schrijvers', 16, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'David', 'Okereke', 21, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Youssouph', 'Badji', 27, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Emmanuel B.', 'Dennis', 42, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Bas', 'Dost', 29, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  
  (@Gent, 'Sinan'		, 'Bolat', 1, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Colin'		, 'Coosemans', 26, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Davy'		, 'Roef', 33, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Andreas'		, 'Hanche-Olsen', 0, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Michael'		, 'Ngadeu', 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Alessio'		, 'Castro-Montes', 14, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Milad'		, 'Mohammadi', 15, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Jordan'		, 'Botaka', 17, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Nurio'		, 'Fortuna', 25, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Ibrahima'	, 'Cissé', 28, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Bruno'		, 'Godeau', 31, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Igor'		, 'Plastun', 32, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Dino'		, 'Arslanagic', 36, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Elisha'		, 'Owusu', 6, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Vadis'		, 'Odjidja-Ofoe', 8, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Roman'		, 'Bezus', 9, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Giorgi'		, 'Chakvetadze', 10, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Wouter'		, 'George', 11, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Alexandre'	, 'De Bruyn', 12, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Matisse'		, 'Samoise', 19, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Sulayman'	, 'Marreh', 22, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Sven'		, 'Kums', 24, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Mathéo'		, 'Parmentier', 27, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Niklas'		, 'Dorsch', 30, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Julien'		, 'De Sart', 13, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@Gent, 'Roman'		, 'Yaremchuk', 7, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Anderson'	, 'Niangbo', 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Dylan'		, 'Mbayo', 18, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Osman'		, 'Bukari', 20, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Laurent'		, 'Depoitre', 29, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Tim'			, 'Kleindienst', 34, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Gianni'		, 'Bruno', 19, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Tarik'		, 'Tissoudali', 34, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),


  (@CercleBrugge, 'Thomas', 'Didillon', 1, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Sébastien', 'Bruzzese', 89, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Miguel', 'Van Damme', 16, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Merveille', 'Goblet', 18, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Warleson', 'Steillon Oliveira', 21, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Victor Alexander', 'da Silva (Vitinho)', 2, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Alexander', 'Corryn', 25, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Boris', 'Popovic', 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Serge-Philippe', 'Raux-Yao', 17, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'David', 'Bates', 3, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Jean Harisson', 'Marcelin', 24, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Jérémy', 'Taravel', 4, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Naomichi', 'Ueda', 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Dimitar', 'Velkovski', 19, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Arne', 'Cassaert', 32, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Robbe', 'Decostere', 8, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Giulian', 'Biancone', 41, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Aldom', 'Deuro', 6, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Franck', 'Kanouté', 98, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Leonardo', 'Da Silva Lopes', 42, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Johanna', 'Omolo', 15, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Kevin', 'Hoggas', 20, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Charles', 'Vanhoutte', 14, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Calvin', 'Dekuyper', 26, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Andi', 'Koshi', 44, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Thibo', 'Somers', 34, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Waldo', 'Rubio', 7, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@CercleBrugge, 'Iké', 'Ugbo', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Anthony', 'Musaba', 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Dino', 'Hotic', 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Olivier', 'Deman', 23, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, 'Alejandro', 'Millàn', 29, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),

  (@Beerschot, 'Wouter', 'Biebauw', 1, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, 'Mike', 'Vanhamel', 31, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, 'Antoine', 'Lejoly', 72, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, 'Jan', 'Van Den Bergh', 2, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, 'Denis', 'Prychynenko', 3, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, 'Frédéric', 'Frans', 4, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, 'Dario', 'Van Den Buijs', 6, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, 'Pierre', 'Bourdin', 15, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, 'Yan', 'Vorogovskiy', 24, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, 'Réda', 'Halaimia', 27, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, 'Ayrton', 'Mboko', 79, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, 'Grégory', 'Grisez', 89, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, 'Joren', 'Dom', 5, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, 'Raphael', 'Holzhauser', 8, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, 'Tom', 'Pietermaat', 16, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, 'Ryan', 'Sanusi', 18, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, 'Keres', 'Masangu', 19, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, 'Ismaila', 'Coulibaly', 28, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, 'Blessing', 'Eleke', 7, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, 'Marius', 'Noubissi', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, 'Musashi', 'Suzuki', 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, 'Abdoulie', 'Sanyang', 22, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@Beerschot, 'Tarik', 'Tissoudali', 34, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, 'Loris', 'Brogno', 92, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, 'Micael', 'Felipe', 99, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, 'Issa', 'Soumaré', 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),

  (@StandardLuik, 'Jean-François'	, 'Gillet'			, 1, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'Arnaud'			, 'Bodart'			, 16, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'Laurent'			, 'Henkinet'		, 30, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'Zinho'			, 'Vanheusden'		, 3, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'Moussa'			, 'Sissako'			, 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'Noë'				, 'Dusenne'			, 6, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'Collins'			, 'Fai'				, 21, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'Nicolas'			, 'Gavory'			, 24, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'Laurent'			, 'Jans'			, 27, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'Damjan'			, 'Pavlovic'		, 33, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'Konstantinos'	, 'Laifis'			, 34, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'Gojko'			, 'Cimirot'			, 8, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'Mehdi'			, 'Carcela-Gonzalez', 10, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'William'			, 'Balikwisha'		, 11, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'Eddy'			, 'Sylvestre'		, 12, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'Eden'			, 'Shamir'			, 15, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'Aleksander'		, 'Boljević'		, 18, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'Selim'			, 'Amallah'			, 19, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'Merveille Bope'	, 'Bokadi'			, 20, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'Maxime'			, 'Lestienne'		, 22, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'Nicolas'			, 'Raskin'			, 26, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'Samuel'			, 'Bastien'			, 28, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'Joachim'			, 'Carcela-Gonzalez', 29, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@StandardLuik, 'Duje'			, 'Cop'				, 7, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'João'			, 'Klauss'			, 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'Jackson'			, 'Muleka'			, 17, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'Abdoul Fessal'	, 'Tapsoba'			, 23, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'Felipe'			, 'Avenatti'		, 25, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'Michel-Ange'		, 'Balikwisha'		, 32, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, 'Denis '			, 'Drăguș'			, 7, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),

  (@OHL, 'Oregan', 'Ravet', 38, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Daniel', 'Iversen', 21, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Rafael', 'Romo', 90, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Frédéric', 'Duplus', 19, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Kenneth', 'Schuermans', 4, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Derrick', 'Tshimanga', 3, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Sascha', 'Kotysch', 23, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Pierre-Yves', 'Ngawa', 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Jordy', 'Gillekens', 27, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Toon', 'Raemaekers', 28, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Barnabás', 'Bese', 18, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Vaclav', 'Jemelka', 2, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Casper', 'De Norre', 24, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Cenk', 'Özkacar', 35, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'David', 'Hubert', 6, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Samy', 'Kehli', 17, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Mathieu', 'Maertens', 33, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Olivier', 'Myny', 22, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Kamal', 'Sowah', 14, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@OHL, 'Aboubakar', 'Keita', 99, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Xavier', 'Mercier', 10, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Tom', 'Van Hyfte', 8, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Isaac', 'Asante', 20, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Thibault', 'Vlietinck', 11, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Kristiyan', 'Malinov', 29, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Levan', 'Shengelia', 19, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Alexis', 'De Sart', 25, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Yanick', 'Aguemon', 7, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Thomas', 'Henry', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Milan', 'Tucic', 30, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Jérémy', 'Perbet', 43, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Tristan', 'Borges', 24, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Stallone', 'Limbombe', 12, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Yohan', 'Croizet', 77, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Daan', 'Vekemans', 32, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Arthur', 'Allemeersch', 39, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Jonah', 'Oasbutey', 45, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Josh', 'Eppiah', 26, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Mousa', 'Tamari', 13, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, 'Siebe', 'Schrijvers', 16, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),

  (@Kortrijk, 'Maxim', 'De Man', 16, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, 'Adam', 'Jakubech', 1, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, 'Marko', 'Ilić', 31, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, 'Timothy', 'Derijck', 76, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, 'Kristof', 'D''Haene', 30, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, 'Lucas', 'Rougeaux', 6, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, 'Trent', 'Sainsbury', 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, 'Gilles', 'Dewaele', 4, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, 'Brendan', 'Hines-Ike', 3, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, 'Petar', 'Golubovic', 2, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, 'Yani', 'Van Den Bossche', 41, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, 'Michiel', 'Jonckheere', 27, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, 'Yevhen', 'Makarenko', 25, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@Kortrijk, 'Julien', 'De Sart', 23, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, 'Sambou', 'Sissoko', 20, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, 'Christophe', 'Lepoint', 15, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, 'Hannes', 'Van Der Bruggen', 14, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, 'Eric', 'Ocansey', 51, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, 'Muhammed', 'Badamosi', 19, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, 'Pape Habib', 'Guèye', 17, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, 'Jovan', 'Stojanović', 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, 'Faïz', 'Selemani', 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, 'Teddy', 'Chevalier', 34, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, 'Hakim', 'Luqman', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  -- (@Kortrijk, 'Ilombé', 'Mboyo', 7, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, 'Amadu', 'Jalloh', 22, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  
  (@Charleroi, 'Nicolas', 'Penneteau', 1, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Joachim', 'Imbrechts', 14, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Rémy', 'Descamps', 40, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Steeven', 'Willems', 23, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Dorian', 'Dessoleil', 24, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Gjoko', 'Zajkov', 6, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Modou', 'Diagne', 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Joris', 'Kayembe', 12, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Ivan', 'Goranov', 2, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Jules', 'Van Cleemput', 4, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Jon', 'Flanagan', 20, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Christophe', 'Diandy', 13, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Gaëtan', 'Hendrickx', 22, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Marco', 'Ilaimaharitra', 26, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Ali', 'Gholizadeh', 8, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Massimo', 'Bruno', 77, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Ryota', 'Morioka', 44, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Ken', 'Nkuba', 28, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Mamadou', 'Fall', 27, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Amine', 'Benchaib', 34, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Guillaume', 'Gillet', 30, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Lucas', 'Ribeiro Costa', 19, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Aboubakar', 'Keita', 88, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Shamar', 'Nicholson', 16, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Anthony', 'Descotte', 15, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Kaveh', 'Rezaei', 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Lukasz', 'Teodorczyk', 91, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Saido', 'Berahino', 38, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Chris', 'Bedia', 18, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Anass', 'Zaroury', 70, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, 'Adem', 'Zorgane', 48, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  
  (@Mechelen, 'Gaëtan', 'Coucke', 1, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Sofiane', 'Bouzian', 12, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Yannick', 'Thoelen', 15, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Maxime', 'Wenssens', 32, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Lucas', 'Bijker', 3, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Sheldon', 'Bateau', 4, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Sandy', 'Walsh', 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Rocky', 'Bushiri', 6, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Siemen', 'Voet', 14, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Dylan', 'Dassy', 22, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Thibaut', 'Peyre', 23, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Victor', 'Wernersson', 26, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Issa', 'Kabore', 29, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Jordi', 'Vanlerberghe', 30, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Geoffry', 'Hairemans', 7, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Onur', 'Kaya', 8, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Joachim', 'Van Damme', 13, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Rob', 'Schoofs', 16, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Trova', 'Boni', 17, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Lars', 'Coveliers', 18, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Bas', 'Van Den Eynden', 37, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Aster', 'Vranckx', 40, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Souza', 'Vinícius', 33, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'William', 'Togui', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Igor', 'De Camargo', 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Nikola', 'Storm', 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Kerim', 'Mrabti', 19, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Gustav', 'Engvall', 20, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Niklo', 'Dailly', 21, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Maryan', 'Shved', 35, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Ferdy', 'Druijf', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, 'Hugo', 'Cuypers', 14, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  
  (@Oostende, 'Jordy', 'Schelfhout', 94, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Guillaume', 'Hubert', 28, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Bram', 'Castro', 99, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Theo', 'Ndicka', 20, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Arthur', 'Theate', 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Jack', 'Hendry', 4, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Frederik', 'Jäkel', 15, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Anton', 'Tanghe', 33, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Brecht', 'Capon', 27, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Ari', 'Skulason', 23, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Marvin', 'Dewaele', 12, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Alfons', 'Amade', 23, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Evangelos', 'Patoulidis', 24, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Maxime', 'D''Arpino', 6, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Andrew', 'Hjulsager', 17, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Nick', 'Bätzner', 34, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Jelle', 'Bataille', 25, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Cameron', 'McGeehan', 18, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Robbie', 'D''Haese', 29, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Indy', 'Boonen', 11, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Kevin', 'Vandendriessche', 26, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Francois', 'Marquet', 8, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Fashion Junior', 'Sakala', 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Mamadou', 'Thiam', 19, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Marko', 'Kvasina', 21, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Sindrit', 'Guri', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Makhtar', 'Gueye', 7, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Jorben', 'Vanhulle', 73, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, 'Thierry', 'Ambrose', 68, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  
  --(@Anderlecht, 'Timon',	'Wellenreuther'		, 1	, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Warner',	'Hahn'				, 24, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Rik',		'Vercauteren'		, 70, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Hendrik',	'Van Crombrugge'	, 30, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Hannes',	'Delcroix'			, 3	, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Wesley',	'Hoedt'				, 4	, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Derrick',	'Van Luckassen'		, 32, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Mohamed',	'Bouchouari'		, 34, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Bohdan',	'Mykhaylychenko'	, 14, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Matt',		'Miazga'			, 20, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Ognjen',	'Vranješ'			, 21, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Elias',	'Cobbaut'			, 22, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Killian',	'Sardella'			, 54, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Marco',	'Kana'				, 55, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Amir',		'Murillo'			, 62, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Kemar',	'Lawrence'			, 92, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Antonio',	'Milic'				, 44, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Anthony',	'Vanden Borre'		, 18, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Zakaria',	'Bakkali'			, 99, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Francis',	'Amuzu'				, 7	, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Josh',		'Cullen'			, 8	, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Michel',	'Vlap'				, 10, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Peter',	'Žulj'				, 23, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Anouar',	'Ait El Hadj'		, 46, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Sergio',	'Gómez'				, 17, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@Anderlecht, 'Albert',	'Sambi Lokonga'		, 48, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Yari',		'Verschaeren'		, 51, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Adrien',	'Trebel'			, 25, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@Anderlecht, 'Lukas',	'Nmecha'			, 7	, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Benito',	'Raman'				, 9	, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Ilias',	'Takidine'			, 27, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@Anderlecht, 'Landry',	'Dimata'			, 9	, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Lior'	,	'Refaelov'			, 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Antoine',	'Colassin'			, 53, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Paul',		'Mukairu'			, 12, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Mustapha', 'Bundu'				, 19, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Isaac',	'Thelin'			, 24, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Joshua',	'Zirkzee'			, 24, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Anderlecht, 'Christian','Kouamé'			, 99, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  
  (@Moucron, 'Vaso', 'Vasic', 90, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Lillo', 'Guarneri', 88, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Nick', 'Gillekens', 34, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Hervé', 'Koffi', 16, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'El Hadji', 'Gueye', 4, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Matias', 'Silvestre', 26, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Eric Junior', 'Bocat', 22, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Saad', 'Agouzoul', 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'William', 'Simba', 40, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Alessandro', 'Ciranni', 13, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Kouadio-Yves', 'Dabila', 2, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Robbe', 'Quirynen', 18, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Marko', 'Bakić', 10, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Deni', 'Hočko', 6, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Dimitri', 'Mohamed', 11, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Benjamin', 'Van Durmen', 30, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Fabrice', 'Olinga', 7, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Enes', 'Saglik', 28, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Junior', 'Onana', 8, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Darly', 'N''Landu', 39, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Bruno', 'Xadas', 23, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Mathéo', 'Vroman', 19, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Alexandre', 'Ippolito', 27, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Béni', 'Badibanga', 29, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Harlem', 'Gnohéré', 31, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Virgiliu', 'Postolachi', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Babacar', 'Dione', 17, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Agim', 'Zeka', 45, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Charles-Andreas', 'Brym', 25, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Imad', 'Faraj', 14, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Serge', 'Tabekou', 70, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Osvaldo Pedro', 'Capemba', 15, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, 'Nuno', 'Da Costa', 20, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),

  (@Genk, 'Danny', 'Vukovic', 1, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, 'Maarten', 'Vandevoordt', 26, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, 'Tobe', 'Leysen', 40, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, 'Dries', 'Wouters', 4, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, 'Gerardo', 'Arteaga', 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, 'Jere', 'Uronen', 21, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, 'Daniel', 'Muñoz', 23, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, 'Jhon', 'Lucumi', 33, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, 'Shawn', 'Adewoye', 35, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, 'Carlos', 'Cuesta', 46, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, 'Bryan', 'Heynen', 8, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, 'Bastien', 'Toma', 11, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, 'Patrik', 'Hrošovský', 17, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, 'Elias', 'Sierra', 19, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, 'Mats Møller', 'Dæhli', 20, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, 'Luca', 'Oyen', 24, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, 'Eboue', 'Kouassi', 38, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, 'Kristian', 'Thorstvedt', 42, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, 'Pierre', 'Dwomon', 80, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, 'Junya', 'Ito', 7, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, 'Cyriel', 'Dessers', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, 'Théo', 'Bongonda', 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, 'Paul', 'Onuachu', 18, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, 'Bryan', 'Limbombe', 22, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, 'Iké', 'Ugbo', 21, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, 'Joseph', 'Paintsil', 28, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),

  (@STVV, 'Kenny', 'Steppe', 1, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Daniel', 'Schmidt', 21, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Wim', 'Vanmarsenille', 35, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Ko', 'Matsubara', 2, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Maximiliano', 'Caufriez', 3, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Pol', 'García', 4, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Ibrahima', 'Sankhon', 8, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Liberato', 'Cacace', 13, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Samy', 'Mmaee', 20, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Jorge', 'Teixeira', 26, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Siebren', 'Lathouwers', 31, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Jonathan', 'Buatu', 39, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Georgios', 'Vagiannidis', 77, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Santiago', 'Colombatto', 5, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Lee', 'Seung-Woo', 10, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Samuel', 'Asamoah', 12, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Stan', 'Van Dessel', 19, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Mory', 'Konaté', 24, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Chris', 'Durkin', 32, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Jhonny', 'Lucas', 33, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Hamza', 'Massoudi', 70, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Christian', 'Brüls', 44, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Yuma', 'Suzuki', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Oleksandr', 'Filippov', 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@STVV, 'Keito', 'Nakamura', 15, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Steve', 'De Ridder', 16, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Facundo', 'Colidio', 18, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Wolke', 'Janssens', 22, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Tatsuya', 'Ito', 23, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Nelson', 'Balongo', 30, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Duckens', 'Nazon', 90, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Ilombé', 'Mboyo', 7, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, 'Daichi', 'Hayashi', 15, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  
  (@WaaslandBeveren, 'Nordin', 'Jackers', 1, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Lucas', 'Pirard', 21, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Brent', 'Gabriël', 44, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Vladimir', 'Van De Wiel - Novinchanova', 2, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Brendan', 'Schoonbaert', 3, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Felix', 'Bastians', 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Andreas', 'Wiegel', 7, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Dries', 'Wuytens', 15, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Alexis', 'Gamboa', 19, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Andrija', 'Vukčević', 22, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Serge', 'Leuko', 23, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Amine', 'Khammas', 24, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Aleksandar', 'Vukotić', 26, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Jenthe', 'Mertens', 27, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Miguel', 'Vieira', 37, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Jur', 'Schryvers', 52, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Georges', 'Mandjeck', 4, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Leonardo', 'Bertone', 6, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Djihad', 'Bizimana', 8, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Denzel', 'Jubitana', 14, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Daan', 'Heymans', 18, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Nikola', 'Pejčić', 20, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Melvin', 'Sitti', 28, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Matthias', 'Verreth', 29, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Milan', 'De Mey', 88, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Jordan', 'Faucher', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Danel', 'Sinani', 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Joseph', 'Efford', 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Alessandro', 'Albanese', 12, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Aboubakary', 'Koita', 17, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Tom', 'Reyners', 77, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, 'Din', 'Sula', 98, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  -- ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Michael', 'Frey', 99, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  
  (@Eupen, 'Tom', 'Roufosse', 30, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Abdul Manaf', 'Nurudeen', 33, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Ortwin', 'De Wolf', 1, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Théo', 'Defourny', 31, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Jordi', 'Amat', 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Senna', 'Miangue', 23, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Benoît', 'Poulain', 6, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Adriano', 'Correia', 21, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Silas', 'Gnaka', 24, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Gary', 'Magnée', 15, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Boris', 'Lambert', 35, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Menno', 'Koch', 3, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Andreas', 'Beck', 32, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Emmanuel', 'Sowah Adjel', 25, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Emmanuel', 'Agbadou', 22, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Tyreek', 'Magee', 14, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Marciano', 'Aziz', 20, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Victor', 'Vázquez', 4, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Sibiry', 'Keita', 13, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Jens', 'Cools', 26, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Jonathan', 'Heris', 28, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Stef', 'Peeters', 8, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Pierre Ramses', 'Akono', 28, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Edo', 'Kayembe', 39, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Konan', 'N''Dri', 34, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Knowledge', 'Musona', 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Amara', 'Baby', 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Mamadou', 'Koné', 77, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Carlos', 'Embalo', 17, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Isaac', 'Nuhu', 29, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Julien', 'Ngoy', 7, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, 'Small', 'Prevljak', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  
  (@ZulteWaregem, 'Sammy', 'Bossut', 1, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, 'Louis', 'Bostyn', 25, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, 'Eike', 'Bansen', 44, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, 'William', 'Bianda', 2, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, 'Olivier', 'Deschacht', 3, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, 'Daniel', 'Opare', 4, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, 'Ewoud', 'Pletinckx', 24, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, 'Laurens', 'De Bock', 27, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, 'Ali Mohamed', 'Abdallah', 31, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, 'Cameron', 'Humphreys', 33, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, 'Nikos', 'Kainourgios', 43, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, 'Damien', 'Marcq', 5, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, 'Abdoulaye', 'Sissako', 6, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, 'Omar', 'Govea', 10, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, 'Bassem', 'Srarfi', 11, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, 'Ibrahima', 'Seck', 21, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, 'Jannes', 'Van Hecke', 67, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, 'Mikael', 'Soisalo', 71, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, 'Jelle', 'Vossen', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, 'Tomáš', 'Chorý', 15, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, 'Jean-Luc', 'Dompe', 17, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@ZulteWaregem, 'Gianni', 'Bruno', 19, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, 'Mathieu', 'De Smet', 29, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, 'Zinho', 'Gano', 93, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed')
  