INSERT INTO [Stats].Stadiums
([Name], [PictureUrl], CreatedUtc, CreatedBy, ModifiedUtc, ModifiedBy)
VALUES
  ('Jan Breydelstadion', '', GETDATE(), 'Seed', GETDATE(), 'Seed')
, ('Bosuilstadion', '', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('Ghelamco Arena', '', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('Olympisch Stadion', '', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('Maurice Dufrasnestadion', '', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('King Power at Den Dreef', '', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('Guldensporenstadion', '', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('Stade du Pays de Charleroi', '', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('AFAS Stadion', '', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('Diaz Arena', '', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('Lotto Park', '', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('Le Canonnier', '', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('Luminus Arena', '', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('Stayen', '', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('Freethielstadion', '', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('Kehrweg-Stadion', '', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('Regenboogstadion', '', GETDATE(), 'Seed', GETDATE(), 'Seed') 
, ('Joseph Marien Stadion', '', GETDATE(), 'Seed', GETDATE(), 'Seed')
, ('Pairaystadion', '', GETDATE(), 'Seed', GETDATE(), 'Seed') 