DECLARE 
	@Anderlecht BIGINT =	(SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'),
	@Antwerp BIGINT =		(SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Antwerp FC%'),
	@Beerschot BIGINT =		(SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'),
	@CercleBrugge BIGINT =	(SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'),
	@ClubBrugge BIGINT =	(SELECT Id FROM Stats.Teams WHERE [Name] like '%Club Brugge%'),
	@Charleroi BIGINT =		(SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'),
	@Eupen BIGINT =			(SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'),
	@Genk BIGINT =			(SELECT Id FROM Stats.Teams WHERE [Name] like '%KRC Genk%'),
	@Gent BIGINT =			(SELECT Id FROM Stats.Teams WHERE [Name] like '%KAA Gent%'),
	@Mechelen BIGINT =		(SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'),
	@Kortrijk BIGINT =		(SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'),
	@OHL BIGINT =			(SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'),
	@Oostende BIGINT =		(SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'),
	@Seraing BIGINT =		(SELECT Id FROM Stats.Teams WHERE [Name] like '%RFC Seraing%'),
	@StandardLuik BIGINT =	(SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'),
	@STVV BIGINT =			(SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'),
	@ZulteWaregem BIGINT =	(SELECT Id FROM Stats.Teams WHERE [Name] like '%Zulte Waregem%'),
	@Union BIGINT =			(SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%')

INSERT INTO Stats.Players
(TeamId, FirstName, LastName, ShirtNumber, Position, CreatedUtc, CreatedBy, ModifiedUtc, ModifiedBy)
VALUES
  (@Antwerp, 'Jean', 'Butez', 46, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Davor', 'Matijaš', 71, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Alireza', 'Beiranvand', 1, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Bruny', 'Nsimba', 22, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Guy', 'Mbenza Kamboleke', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Didier', 'Lamkel Ze', 7, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Ivo', 'Rodrigues', 8, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Dieumerci', 'Mbokani', 70, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Christian', 'Benavente Bristol', 24, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Birger', 'Verstraete', 5, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Nana', 'Ampomah', 23, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Nill', 'De Pauw', 14, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Manuel', 'Benson', 28, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Koji', 'Miyoshi', 19, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Pieter', 'Gerkens', 16, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Louis', 'Verstraete', 33, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Sander', 'Cooman', 20, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Alexis', 'De Sart', 25, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Lior', 'Refaelov', 11, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Faris', 'Haroun', 38, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Dragan', 'Lausberg', 64, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Luete Ava', 'Dongo', 12, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Jordan', 'Lukaku', 94, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Jérémy', 'Gelin', 26, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Frank', 'Boya', 15, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Ritchie', 'De Laet', 2, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Júnior', 'Pius', 40, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Abdoulaye', 'Seck', 4, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Aurélio', 'Buta', 30, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Dylan', 'Batubinsika', 21, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Simen', 'Juklerød', 6, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Antwerp, 'Michael', 'Frey', 99, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),


  (@ClubBrugge, 'Ethan', 'Horvath', 22, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Nick', 'Shinton', 33, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Simon', 'Mignolet', 88, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Senne', 'Lammens', 91, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Eduard', 'Sobol', 2, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Odilon', 'Kossounou', 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Matej', 'Mitrovic', 15, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Simon', 'Deli', 17, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Federico', 'Ricca', 18, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Ignace', 'Van Der Brempt', 28, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Brandon', 'Mechele', 44, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Clinton', 'Mata', 77, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Éder', 'Balanta', 3, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Krépin', 'Diatta', 11, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Hans', 'Vanaken', 20, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Ruud', 'Vormer', 25, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Mats', 'Rits', 26, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Maxim', 'De Cuyper', 55, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Charles', 'De Ketelaere', 90, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Thomas', 'Van Den Keybus', 97, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Amadou', 'Sagna', 7, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Michael', 'krmenčík', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Noa', 'Lang', 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Siebe', 'Schrijvers', 16, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'David', 'Okereke', 21, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Youssouph', 'Badji', 27, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Emmanuel B.', 'Dennis', 42, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, 'Bas', 'Dost', 29, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  
  (@Gent, 'Sinan', 'Bolat', 1, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Colin', 'Coosemans', 26, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Davy', 'Roef', 33, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Andreas', 'Hanche-Olsen', 0, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Michael', 'Ngadeu', 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Alessio', 'Castro-Montes', 14, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Milad', 'Mohammadi', 15, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Jordan', 'Botaka', 17, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Nurio', 'Fortuna', 25, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Ibrahima', 'Cissé', 28, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Bruno', 'Godeau', 31, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Igor', 'Plastun', 32, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Dino', 'Arslanagic', 36, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Elisha', 'Owusu', 6, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Vadis', 'Odjidja-Ofoe', 8, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Roman', 'Bezus', 9, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Giorgi', 'Chakvetadze', 10, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Wouter', 'George', 11, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Alexandre', 'De Bruyn', 12, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Matisse', 'Samoise', 19, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Sulayman', 'Marreh', 22, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Sven', 'Kums', 24, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Mathéo', 'Parmentier', 27, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Niklas', 'Dorsch', 30, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Roman', 'Yaremchuk', 7, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Anderson', 'Niangbo', 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Dylan', 'Mbayo', 18, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Osman', 'Bukari', 20, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Laurent', 'Depoitre', 29, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, 'Tim', 'Kleindienst', 34, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),

  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Thomas', 'Didillon', 1, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Sébastien', 'Bruzzese', 89, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Miguel', 'Van Damme', 16, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Merveille', 'Goblet', 18, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Warleson', 'Steillon Oliveira', 21, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Victor Alexander', 'da Silva (Vitinho)', 2, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Alexander', 'Corryn', 25, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Serge-Philippe', 'Raux-Yao', 17, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'David', 'Bates', 3, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Jean Harisson', 'Marcelin', 24, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Jérémy', 'Taravel', 4, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Naomichi', 'Ueda', 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Dimitar', 'Velkovski', 19, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Arne', 'Cassaert', 32, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Robbe', 'Decostere', 8, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Giulian', 'Biancone', 41, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Aldom', 'Deuro', 6, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Franck', 'Kanouté', 98, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Leonardo', 'Da Silva Lopes', 42, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Johanna', 'Omolo', 15, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Kevin', 'Hoggas', 20, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Charles', 'Vanhoutte', 14, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Calvin', 'Dekuyper', 26, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Andi', 'Koshi', 44, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Thibo', 'Somers', 34, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Kylian', 'Hazard', 7, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Iké', 'Ugbo', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Anthony', 'Musaba', 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Dino', 'Hotic', 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'), 'Olivier', 'Deman', 23, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),

  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'), 'Wouter', 'Biebauw', 1, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'), 'Mike', 'Vanhamel', 31, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'), 'Antoine', 'Lejoly', 72, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'), 'Jan', 'Van Den Bergh', 2, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'), 'Denis', 'Prychynenko', 3, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'), 'Frédéric', 'Frans', 4, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'), 'Dario', 'Van Den Buijs', 6, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'), 'Pierre', 'Bourdin', 15, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'), 'Yan', 'Vorogovskiy', 24, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'), 'Réda', 'Halaimia', 27, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'), 'Ayrton', 'Mboko', 79, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'), 'Grégory', 'Grisez', 89, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'), 'Joren', 'Dom', 5, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'), 'Raphael', 'Holzhauser', 8, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'), 'Tom', 'Pietermaat', 16, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'), 'Ryan', 'Sanusi', 18, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'), 'Keres', 'Masangu', 19, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'), 'Ismaila', 'Coulibaly', 28, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'), 'Blessing', 'Eleke', 7, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'), 'Marius', 'Noubissi', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'), 'Musashi', 'Suzuki', 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'), 'Abdoulie', 'Sanyang', 22, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'), 'Tarik', 'Tissoudali', 34, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'), 'Loris', 'Brogno', 92, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'), 'Micael', 'Felipe', 99, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),

  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Jean-François', 'Gillet', 1, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Arnaud', 'Bodart', 16, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Laurent', 'Henkinet', 30, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Zinho', 'Vanheusden', 3, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Moussa', 'Sissako', 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Noë', 'Dusenne', 6, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Collins', 'Fai', 21, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Nicolas', 'Gavory', 24, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Laurent', 'Jans', 27, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Damjan', 'Pavlovic', 33, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Konstantinos', 'Laifis', 34, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Gojko', 'Cimirot', 8, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Mehdi', 'Carcela-Gonzalez', 10, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'William', 'Balikwisha', 11, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Eddy', 'Sylvestre', 12, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Eden', 'Shamir', 15, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Aleksander', 'Boljević', 18, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Selim', 'Amallah', 19, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Merveille Bope', 'Bokadi', 20, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Maxime', 'Lestienne', 22, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Nicolas', 'Raskin', 26, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Samuel', 'Bastien', 28, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Joachim', 'Carcela-Gonzalez', 29, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Duje', 'Cop', 7, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Obbi', 'Oulare', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Jackson', 'Muleka', 17, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Abdoul Fessal', 'Tapsoba', 23, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Felipe', 'Avenatti', 25, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'), 'Michel-Ange', 'Balikwisha', 32, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),

  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Oregan', 'Ravet', 38, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Daniel', 'Iversen', 21, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Rafael', 'Romo', 90, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Frédéric', 'Duplus', 19, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Kenneth', 'Schuermans', 4, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Derrick', 'Tshimanga', 3, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Sascha', 'Kotysch', 23, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Pierre-Yves', 'Ngawa', 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Jordy', 'Gillekens', 27, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Toon', 'Raemaekers', 28, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Barnabás', 'Bese', 18, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Vaclav', 'Jemelka', 2, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Casper', 'De Norre', 24, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'David', 'Hubert', 6, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Samy', 'Kehli', 17, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Mathieu', 'Maertens', 33, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Olivier', 'Myny', 22, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Kamal', 'Sowah', 14, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Aboubakar', 'Keita', 99, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Xavier', 'Mercier', 10, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Tom', 'Van Hyfte', 8, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Isaac', 'Asante', 20, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Thibault', 'Vlietinck', 11, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Kristiyan', 'Malinov', 29, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Yanick', 'Aguemon', 7, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Thomas', 'Henry', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Milan', 'Tucic', 30, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Jérémy', 'Perbet', 43, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Tristan', 'Borges', 24, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Stallone', 'Limbombe', 12, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Yohan', 'Croizet', 77, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Daan', 'Vekemans', 32, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Arthur', 'Allemeersch', 39, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Jonah', 'Oasbutey', 45, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Josh', 'Eppiah', 26, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'), 'Mousa', 'Tamari', 13, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),

  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'), 'Maxim', 'De Man', 16, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'), 'Adam', 'Jakubech', 1, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'), 'Marko', 'Ilić', 31, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'), 'Timothy', 'Derijck', 76, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'), 'Kristof', 'D''Haene', 30, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'), 'Lucas', 'Rougeaux', 6, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'), 'Trent', 'Sainsbury', 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'), 'Gilles', 'Dewaele', 4, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'), 'Brendan', 'Hines-Ike', 3, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'), 'Petar', 'Golubovic', 2, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'), 'Yani', 'Van Den Bossche', 41, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'), 'Michiel', 'Jonckheere', 27, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'), 'Yevhen', 'Makarenko', 25, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'), 'Julien', 'De Sart', 23, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'), 'Sambou', 'Sissoko', 20, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'), 'Christophe', 'Lepoint', 15, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'), 'Hannes', 'Van Der Bruggen', 14, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'), 'Eric', 'Ocansey', 51, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'), 'Muhammed', 'Badamosi', 19, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'), 'Pape Habib', 'Guèye', 17, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'), 'Jovan', 'Stojanović', 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'), 'Faïz', 'Selemani', 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'), 'Teddy', 'Chevalier', 34, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'), 'Hakim', 'Luqman', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'), 'Ilombé', 'Mboyo', 7, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'), 'Amadu', 'Jalloh', 22, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Nicolas', 'Penneteau', 1, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Joachim', 'Imbrechts', 14, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Rémy', 'Descamps', 40, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Steeven', 'Willems', 23, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Dorian', 'Dessoleil', 24, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Gjoko', 'Zajkov', 6, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Modou', 'Diagne', 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Joris', 'Kayembe', 12, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Ivan', 'Goranov', 2, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Jules', 'Van Cleemput', 4, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Jon', 'Flanagan', 20, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Christophe', 'Diandy', 13, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Gaëtan', 'Hendrickx', 22, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Marco', 'Ilaimaharitra', 26, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Ali', 'Gholizadeh', 8, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Massimo', 'Bruno', 77, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Ryota', 'Morioka', 44, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Ken', 'Nkuba', 28, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Mamadou', 'Fall', 27, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Amine', 'Benchaib', 34, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Guillaume', 'Gillet', 30, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Lucas', 'Ribeiro Costa', 19, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Shamar', 'Nicholson', 16, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Anthony', 'Descotte', 15, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Kaveh', 'Rezaei', 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Lukasz', 'Teodorczyk', 91, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Saido', 'Berahino', 38, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Chris', 'Bedia', 18, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'), 'Anass', 'Zaroury', 70, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Gaëtan', 'Coucke', 1, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Sofiane', 'Bouzian', 12, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Yannick', 'Thoelen', 15, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Maxime', 'Wenssens', 32, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Lucas', 'Bijker', 3, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Sheldon', 'Bateau', 4, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Sandy', 'Walsh', 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Rocky', 'Bushiri', 6, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Siemen', 'Voet', 14, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Dylan', 'Dassy', 22, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Thibaut', 'Peyre', 23, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Victor', 'Wernersson', 26, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Issa', 'Kabore', 29, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Jordi', 'Vanlerberghe', 30, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Geoffry', 'Hairemans', 7, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Onur', 'Kaya', 8, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Joachim', 'Van Damme', 13, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Rob', 'Schoofs', 16, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Trova', 'Boni', 17, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Lars', 'Coveliers', 18, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Bas', 'Van Den Eynden', 37, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Aster', 'Vranckx', 40, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Steven', 'Defour', 88, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'William', 'Togui', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Igor', 'De Camargo', 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Nikola', 'Storm', 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Kerim', 'Mrabti', 19, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Gustav', 'Engvall', 20, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Niklo', 'Dailly', 21, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Maryan', 'Shved', 35, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'), 'Ferdy', 'Druijf', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'), 'Jordy', 'Schelfhout', 94, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'), 'Guillaume', 'Hubert', 28, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'), 'Bram', 'Castro', 99, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'), 'Theo', 'Ndicka', 20, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'), 'Arthur', 'Theate', 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'), 'Jack', 'Hendry', 4, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'), 'Frederik', 'Jäkel', 15, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'), 'Anton', 'Tanghe', 33, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'), 'Brecht', 'Capon', 27, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'), 'Ari', 'Skulason', 23, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'), 'Marvin', 'Dewaele', 12, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'), 'Evangelos', 'Patoulidis', 24, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'), 'Maxime', 'D''Arpino', 6, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'), 'Andrew', 'Hjulsager', 17, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'), 'Nick', 'Bätzner', 34, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'), 'Jelle', 'Bataille', 25, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'), 'Cameron', 'McGeehan', 18, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'), 'Robbie', 'D''Haese', 29, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'), 'Indy', 'Boonen', 11, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'), 'Kevin', 'Vandendriessche', 26, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'), 'Francois', 'Marquet', 8, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'), 'Fashion Junior', 'Sakala', 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'), 'Mamadou', 'Thiam', 19, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'), 'Marko', 'Kvasina', 21, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'), 'Sindrit', 'Guri', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'), 'Makhtar', 'Gueye', 7, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'), 'Jorben', 'Vanhulle', 73, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Timon', 'Wellenreuther', 1, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Lukas', 'Nmecha', 7, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Josh', 'Cullen', 8, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Landry', 'Dimata', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Michel', 'Vlap', 10, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Percy', 'Tau', 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Paul', 'Mukairu', 12, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Bohdan', 'Mykhaylychenko', 14, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Anthony', 'Vanden Borre', 18, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Mustapha', 'Bundu', 19, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Matt', 'Miazga', 20, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Ognjen', 'Vranješ', 21, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Elias', 'Cobbaut', 22, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Peter', 'Žulj', 23, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Warner', 'Hahn', 24, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Adrien', 'Trebel', 25, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Ilias', 'Takidine', 27, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Hendrik', 'Van Crombrugge', 30, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Derrick', 'Van Luckassen', 32, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Mohamed', 'Bouchouari', 34, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Francis', 'Amuzu', 40, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Hannes', 'Delcroix', 42, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Antonio', 'Milic', 44, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Anouar', 'Ait El Hadj', 46, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Albert', 'Sambi Lokonga', 48, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Yari', 'Verschaeren', 51, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Antoine', 'Colassin', 53, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Killian', 'Sardella', 54, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Marco', 'Kana', 55, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Amir', 'Murillo', 62, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Rik', 'Vercauteren', 70, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Kemar', 'Lawrence', 92, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'), 'Zakaria', 'Bakkali', 99, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Vaso', 'Vasic', 90, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Lillo', 'Guarneri', 88, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Nick', 'Gillekens', 34, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Hervé', 'Koffi', 16, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'El Hadji', 'Gueye', 4, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Matias', 'Silvestre', 26, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Eric Junior', 'Bocat', 22, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Saad', 'Agouzoul', 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'William', 'Simba', 40, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Alessandro', 'Ciranni', 13, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Kouadio-Yves', 'Dabila', 2, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Robbe', 'Quirynen', 18, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Marko', 'Bakić', 10, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Deni', 'Hočko', 6, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Dimitri', 'Mohamed', 11, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Benjamin', 'Van Durmen', 30, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Fabrice', 'Olinga', 7, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Enes', 'Saglik', 28, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Junior', 'Onana', 8, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Darly', 'N''Landu', 39, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Bruno', 'Xadas', 23, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Mathéo', 'Vroman', 19, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Alexandre', 'Ippolito', 27, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Béni', 'Badibanga', 29, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Harlem', 'Gnohéré', 31, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Virgiliu', 'Postolachi', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Babacar', 'Dione', 17, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Agim', 'Zeka', 45, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Charles-Andreas', 'Brym', 25, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Imad', 'Faraj', 14, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Serge', 'Tabekou', 70, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Osvaldo Pedro', 'Capemba', 15, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Excel Moeskroen%'), 'Nuno', 'Da Costa', 20, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),

  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KRC Genk%'), 'Danny', 'Vukovic', 1, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KRC Genk%'), 'Maarten', 'Vandevoordt', 26, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KRC Genk%'), 'Tobe', 'Leysen', 40, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KRC Genk%'), 'Dries', 'Wouters', 4, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KRC Genk%'), 'Gerardo', 'Arteaga', 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KRC Genk%'), 'Jere', 'Uronen', 21, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KRC Genk%'), 'Daniel', 'Muñoz', 23, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KRC Genk%'), 'Jhon', 'Lucumi', 33, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KRC Genk%'), 'Shawn', 'Adewoye', 35, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KRC Genk%'), 'Carlos', 'Cuesta', 46, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KRC Genk%'), 'Bryan', 'Heynen', 8, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KRC Genk%'), 'Bastien', 'Toma', 11, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KRC Genk%'), 'Patrik', 'Hrošovský', 17, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KRC Genk%'), 'Elias', 'Sierra', 19, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KRC Genk%'), 'Mats Møller', 'Dæhli', 20, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KRC Genk%'), 'Luca', 'Oyen', 24, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KRC Genk%'), 'Eboue', 'Kouassi', 38, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KRC Genk%'), 'Kristian', 'Thorstvedt', 42, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KRC Genk%'), 'Pierre', 'Dwomon', 80, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KRC Genk%'), 'Junya', 'Ito', 7, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KRC Genk%'), 'Cyriel', 'Dessers', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KRC Genk%'), 'Théo', 'Bongonda', 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KRC Genk%'), 'Paul', 'Onuachu', 18, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KRC Genk%'), 'Bryan', 'Limbombe', 22, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),

  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Kenny', 'Steppe', 1, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Daniel', 'Schmidt', 21, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Wim', 'Vanmarsenille', 35, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Ko', 'Matsubara', 2, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Maximiliano', 'Caufriez', 3, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Pol', 'García', 4, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Ibrahima', 'Sankhon', 8, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Liberato', 'Cacace', 13, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Samy', 'Mmaee', 20, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Jorge', 'Teixeira', 26, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Siebren', 'Lathouwers', 31, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Jonathan', 'Buatu', 39, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Georgios', 'Vagiannidis', 77, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Santiago', 'Colombatto', 5, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Lee', 'Seung-Woo', 10, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Samuel', 'Asamoah', 12, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Stan', 'Van Dessel', 19, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Mory', 'Konaté', 24, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Chris', 'Durkin', 32, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Jhonny', 'Lucas', 33, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Hamza', 'Massoudi', 70, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Yuma', 'Suzuki', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Oleksandr', 'Filippov', 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Keito', 'Nakamura', 15, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Steve', 'De Ridder', 16, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Facundo', 'Colidio', 18, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Wolke', 'Janssens', 22, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Tatsuya', 'Ito', 23, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Nelson', 'Balongo', 30, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'), 'Duckens', 'Nazon', 90, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Nordin', 'Jackers', 1, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Lucas', 'Pirard', 21, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Brent', 'Gabriël', 44, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Vladimir', 'Van De Wiel - Novinchanova', 2, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Brendan', 'Schoonbaert', 3, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Felix', 'Bastians', 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Andreas', 'Wiegel', 7, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Dries', 'Wuytens', 15, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Alexis', 'Gamboa', 19, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Andrija', 'Vukčević', 22, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Serge', 'Leuko', 23, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Amine', 'Khammas', 24, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Aleksandar', 'Vukotić', 26, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Jenthe', 'Mertens', 27, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Miguel', 'Vieira', 37, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Jur', 'Schryvers', 52, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Georges', 'Mandjeck', 4, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Leonardo', 'Bertone', 6, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Djihad', 'Bizimana', 8, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Denzel', 'Jubitana', 14, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Daan', 'Heymans', 18, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Nikola', 'Pejčić', 20, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Melvin', 'Sitti', 28, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Matthias', 'Verreth', 29, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Milan', 'De Mey', 88, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Jordan', 'Faucher', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Danel', 'Sinani', 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Joseph', 'Efford', 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Alessandro', 'Albanese', 12, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Aboubakary', 'Koita', 17, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Tom', 'Reyners', 77, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Din', 'Sula', 98, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  -- ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KVRS Waasland - SK Beveren%'), 'Michael', 'Frey', 99, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Tom', 'Roufosse', 30, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Abdul Manaf', 'Nurudeen', 33, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Ortwin', 'De Wolf', 1, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Théo', 'Defourny', 31, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Jordi', 'Amat', 5, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Senna', 'Miangue', 23, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Benoît', 'Poulain', 6, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Adriano', 'Correia', 21, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Silas', 'Gnaka', 24, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Gary', 'Magnée', 15, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Boris', 'Lambert', 35, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Menno', 'Koch', 3, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Andreas', 'Beck', 32, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Emmanuel', 'Sowah Adjel', 25, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Emmanuel', 'Agbadou', 22, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Tyreek', 'Magee', 14, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Marciano', 'Aziz', 20, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Victor', 'Vázquez', 4, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Sibiry', 'Keita', 13, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Jens', 'Cools', 26, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Jonathan', 'Heris', 28, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Stef', 'Peeters', 8, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Pierre Ramses', 'Akono', 28, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Edo', 'Kayembe', 39, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Konan', 'N''Dri', 34, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Knowledge', 'Musona', 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Amara', 'Baby', 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Mamadou', 'Koné', 77, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Carlos', 'Embalo', 17, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Isaac', 'Nuhu', 29, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Julien', 'Ngoy', 7, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'), 'Small', 'Prevljak', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%SV Zulte Waregem%'), 'Sammy', 'Bossut', 1, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%SV Zulte Waregem%'), 'Louis', 'Bostyn', 25, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%SV Zulte Waregem%'), 'Eike', 'Bansen', 44, 'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%SV Zulte Waregem%'), 'William', 'Bianda', 2, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%SV Zulte Waregem%'), 'Olivier', 'Deschacht', 3, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%SV Zulte Waregem%'), 'Daniel', 'Opare', 4, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%SV Zulte Waregem%'), 'Ewoud', 'Pletinckx', 24, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%SV Zulte Waregem%'), 'Laurens', 'De Bock', 27, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%SV Zulte Waregem%'), 'Ali Mohamed', 'Abdallah', 31, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%SV Zulte Waregem%'), 'Cameron', 'Humphreys', 33, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%SV Zulte Waregem%'), 'Nikos', 'Kainourgios', 43, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%SV Zulte Waregem%'), 'Damien', 'Marcq', 5, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%SV Zulte Waregem%'), 'Abdoulaye', 'Sissako', 6, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%SV Zulte Waregem%'), 'Omar', 'Govea', 10, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%SV Zulte Waregem%'), 'Bassem', 'Srarfi', 11, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%SV Zulte Waregem%'), 'Ibrahima', 'Seck', 21, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%SV Zulte Waregem%'), 'Jannes', 'Van Hecke', 67, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%SV Zulte Waregem%'), 'Mikael', 'Soisalo', 71, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%SV Zulte Waregem%'), 'Jelle', 'Vossen', 9, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%SV Zulte Waregem%'), 'Tomáš', 'Chorý', 15, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%SV Zulte Waregem%'), 'Jean-Luc', 'Dompe', 17, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%SV Zulte Waregem%'), 'Gianni', 'Bruno', 19, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ((SELECT Id FROM Stats.Teams WHERE [Name] like '%SV Zulte Waregem%'), 'Mathieu', 'De Smet', 29, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed')
  