DECLARE 
	@Albania		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Albania%'),
	@Algeria		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Algeria%'),
	@Angola			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Angola%'),
	@Argentina		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Argentina%'),
	@Austria		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Australia%'),
	@Australia		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Austria%'),
	@Belgium		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Belgium%'),
	@Benin			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Benin%'),
	@Bosnia			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Bosnia and Herzegovina%'),
	@Brazil			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Brazil%'),
	@Bulgaria		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Bulgaria%'),
	@BurkinaFaso	BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Burkina Faso%'),
	@Burundi		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Burundi%'),
	@Cameroon		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Cameroon%'),
	@Canada			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Canada%'),
	@CapeVerde		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Cape Verde%'),
	@Chad			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Chad%'),
	@Colombia		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Colombia%'),
	@Comoros		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Comoros%'),
	@CongoDem		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%The Democratic Republic Of The Congo%'),
	@CongoRep		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like 'Congo'),
	@CostaRica		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Costa Rica%'),
	@Croatia		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Croatia%'),
	@Cyprus			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Cyprus%'),
	@CzechRepublic	BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Czech Republic%'),
	@Denmark		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Denmark%'),
	@Finland		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Finland%'),
	@France			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%France%'),
	@Georgia		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Georgia%'),
	@Germany		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Germany%'),
	@Gambia			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Gambia%'),
	@Ghana			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Ghana%'),
	@Greece			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Greece%'),
	@Guinea			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like 'Guinea'),
	@GuineaBissau	BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] = 'Guinea-Bissau'),
	@Haiti			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Haiti%'),
	@Hungary		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Hungary%'),
	@Iceland		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Iceland%'),
	@Iran			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Islamic Republic of Iran%'),
	@Ireland		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Ireland%'),
	@Israel			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Israel%'),
	@Italy			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Italy%'),
	@IvoryCoast		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Côte D''Ivoire%'),
	@Jamaica		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Jamaica%'),
	@Japan			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Japan%'),
	@Jordan			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Jordan%'),
	@Kazakhstan		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Kazakhstan%'),
	@Kenya			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Kenya%'),
	@Luxembourg		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Luxembourg%'),
	@Macedonia		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%the Former Yugoslav Republic Of Macedonia%'),
	@Malaysia		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Malaysia%'),
	@Mali			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Mali%'),
	@Malta			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Malta%'),
	@Mexico			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Mexico%'),
	@Moldova		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Republic of Moldova%'),
	@Montenegro		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Montenegro%'),
	@Morocco		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Morocco%'),
	@Netherlands	BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Netherlands%'),
	@NewZealand		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%New Zealand%'),
	@Norway			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Norway%'),
	@Nigeria		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Nigeria%'),
	@Panama			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Panama%'),
	@Peru			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Peru%'),
	@Poland			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Poland%'),
	@Portugal		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Portugal%'),
	@Romania		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Romania%'),
	@Rwanda			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Rwanda%'),
	@Senegal		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Senegal%'),
	@Serbia			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Serbia%'),
	@SierraLeone	BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Sierra Leone%'),
	@Slovakia		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Slovakia%'),
	@Slovenia		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Slovenia%'),
	@SouthKorea		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Republic of Korea%'),
	@Spain			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Spain%'),
	@Suriname		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Suriname%'),
	@Sweden			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Sweden%'),
	@Switzerland	BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Switzerland%'),
	@Thailand		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Thailand%'),
	@TrinidadTobago	BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Trinidad and Tobago%'),
	@Tunisia		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Tunisia%'),
	@Turkey			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Turkey%'),
	@Ukraine		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Ukraine%'),
	@UnitedKingdom	BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%United Kingdom%'),
	@Uruguay		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Uruguay%'),
	@USA			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%United States%'),
	@Venezuela		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Bolivarian Republic of Venezuela%'),
	@Zambia			BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Zambia%'),
	@Zimbabwe		BIGINT		= (SELECT Id FROM dbo.Countries WHERE [Name] like '%Zimbabwe%')

INSERT INTO [dbo].[Persons]
([FirstName], [LastName], [Nationality], CreatedUtc, CreatedBy, ModifiedUtc, ModifiedBy)
VALUES
  ('Adel'				, 'Adel Bo'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ali Mohamed'		, 'Abdallah'			, @Comoros		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Shawn'				, 'Adewoye'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Emmanuel'			, 'Agbadou'				, @IvoryCoast	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Saad'				, 'Agouzoul'			, @Morocco		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Yanick'				, 'Aguemon'				, @Benin		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Anouar'				, 'Ait El Hadj'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Pierre Ramses'		, 'Akono'				, @Cameroon		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Alessandro'			, 'Albanese'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Arthur'				, 'Allemeersch'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Dinis'				, 'Almeida'				, @Portugal		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Alfons'				, 'Amade'				, @Germany		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Selim'				, 'Amallah'				, @Morocco		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Lazare'				, 'Amani'				, @IvoryCoast	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jordi'				, 'Amat'				, @Spain		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Thierry'			, 'Ambrose'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Nana Opoku'			, 'Ampomah'				, @Ghana		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Francis'			, 'Amuzu'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Dino'				, 'Arslanagic'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Gerardo'			, 'Arteaga'				, @Mexico		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Samuel'				, 'Asamoah'				, @Ghana		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Isaac'				, 'Asante'				, @Ghana		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Kerian'				, 'Atheba'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Felipe'				, 'Avenatti'			, @Uruguay		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Marciano'			, 'Aziz'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Amara'				, 'Baby'				, @Senegal		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Muhammed'			, 'Badamosi'			, @Gambia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Béni'				, 'Badibanga'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Youssouph'			, 'Badji'				, @Senegal		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jonas'				, 'Bager'				, @Denmark		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Marko'				, 'Bakić'				, @Montenegro	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Zakaria'			, 'Bakkali'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Éder Álvarez'		, 'Balanta'				, @Colombia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Michel-Ange'		, 'Balikwisha'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('William'			, 'Balikwisha'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Nelson'				, 'Balongo'				, @CongoDem		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Eike'				, 'Bansen'				, @Germany		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Serkan'				, 'Basha'				, @Albania		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Felix'				, 'Bastians'			, @Germany		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Samuel'				, 'Bastien'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jelle'				, 'Bataille'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Sheldon'			, 'Bateau'				, @TrinidadTobago , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('David'				, 'Bates'				, @UnitedKingdom, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Nick'				, 'Bätzner'				, @Germany		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Dylan'				, 'Batubinsika'			, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Andreas'			, 'Beck'				, @Germany		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Chris'				, 'Bedia'				, @IvoryCoast	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Alireza'			, 'Beiranvand'			, @Iran			, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Christian'			, 'Benavente Bristol'	, @Peru			, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Amine'				, 'Benchaib'			, @Morocco		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Manuel'				, 'Benson'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Yassine'			, 'Ben Hamed'			, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Saido'				, 'Berahino'			, @Burundi		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Antoine'			, 'Bernier'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Leonardo'			, 'Bertone'				, @Switzerland	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Barnabás'			, 'Bese'				, @Hungary		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Roman'				, 'Bezus'				, @Ukraine		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Giulian'			, 'Biancone'			, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('William'			, 'Bianda'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Wouter'				, 'Biebauw'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Lucas'				, 'Bijker'				, @Netherlands	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Djihad'				, 'Bizimana'			, @Rwanda		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Eric Junior'		, 'Bocat'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Arnaud'				, 'Bodart'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Merveille Bope'		, 'Bokadi'				, @CongoDem		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Sinan'				, 'Bolat'				, @Turkey		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Aleksander'			, 'Boljević'			, @Montenegro	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Théo'				, 'Bongonda'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Trova'				, 'Boni'				, @BurkinaFaso	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Indy'				, 'Boonen'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Sofiane'			, 'Bouzian'				, @Morocco		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Tristan'			, 'Borges'				, @Canada		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Sammy'				, 'Bossut'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Louis'				, 'Bostyn'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jordan'				, 'Botaka'				, @CongoDem		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Mohamed'			, 'Bouchouari'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Benjamin'			, 'Boulenger'			, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Pierre'				, 'Bourdin'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Frank'				, 'Boya'				, @Cameroon		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Loris'				, 'Brogno'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Christian'			, 'Brüls'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Gianni'				, 'Bruno'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Massimo'			, 'Bruno'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Sébastien'			, 'Bruzzese'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Charles-Andreas'	, 'Brym'				, @Canada		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jonathan'			, 'Buatu'				, @Angola		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Osman'				, 'Bukari'				, @Ghana		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Mustapha'			, 'Bundu'				, @SierraLeone	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Christian'			, 'Burgess'				, @UnitedKingdom, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Rocky'				, 'Bushiri'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Aurélio'			, 'Buta'				, @Portugal		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jean'				, 'Butez'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Liberato'			, 'Cacace'				, @NewZealand	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Mathieu'			, 'Cachbach'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Osvaldo Pedro'		, 'Capemba'				, @Angola		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Brecht'				, 'Capon'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Mehdi'				, 'Carcela-Gonzalez'	, @Morocco		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Joachim'			, 'Carcela-Gonzalez'	, @Morocco		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Arne'				, 'Cassaert'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Bram'				, 'Castro'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Alessio'			, 'Castro-Montes'		, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Maximiliano'		, 'Caufriez'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Giorgi'				, 'Chakvetadze'			, @Georgia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Teddy'				, 'Chevalier'			, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Tomáš'				, 'Chorý'				, @CzechRepublic, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Gojko'				, 'Cimirot'				, @Bosnia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Alessandro'			, 'Ciranni'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ibrahima'			, 'Cissé'				, @Guinea		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Elias'				, 'Cobbaut'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Antoine'			, 'Colassin'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Facundo'			, 'Colidio'				, @Argentina	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Sander'				, 'Coopman'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Santiago'			, 'Colombatto'			, @Argentina	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jens'				, 'Cools'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Colin'				, 'Coosemans'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Duje'				, 'Cop'					, @Croatia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Adriano'			, 'Correia'				, @Brazil		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Gaëtan'				, 'Coucke'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Yohan'				, 'Croizet'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Alexander'			, 'Corryn'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ismaila'			, 'Coulibaly'			, @Mali			, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Lars'				, 'Coveliers'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Carlos'				, 'Cuesta'				, @Colombia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Josh'				, 'Cullen'				, @Ireland		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Hugo'				, 'Cuypers'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Mats Møller	'		, 'Dæhli'				, @Norway		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Nuno'				, 'Da Costa'			, @CapeVerde	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Leonardo'			, 'Da Silva Lopes'		, @Portugal		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Victor Alexander'	, 'da Silva (Vitinho)'	, @Brazil		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Kouadio-Yves'		, 'Dabila'				, @IvoryCoast	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Niklo'				, 'Dailly'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Dylan'				, 'Dassy'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Robbe'				, 'Decostere'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Calvin'				, 'Dekuyper'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Olivier'			, 'Deman'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Simon'				, 'Deli'				, @IvoryCoast	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Emmanuel B.'		, 'Dennis'				, @Nigeria		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Aldom'				, 'Deuro'				, @Mali			, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Krépin'				, 'Diatta'				, @Senegal		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Thomas'				, 'Didillon'			, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Bas'				, 'Dost'				, @Netherlands	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Maxime'				, 'D''Arpino'			, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Laurens'			, 'De Bock'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Alexandre'			, 'De Bruyn'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Igor'				, 'De Camargo'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Maxim'				, 'De Cuyper'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Charles'			, 'De Ketelaere'		, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ritchie'			, 'De Laet'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Maxim'				, 'De Man'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Milan'				, 'De Mey'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Casper'				, 'De Norre'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Nill'				, 'De Pauw'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Steve'				, 'De Ridder'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Alexis'				, 'De Sart'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Julien'				, 'De Sart'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Mathieu'			, 'De Smet'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ortwin'				, 'De Wolf'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Kristof'			, 'D''Haene'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Robbie'				, 'D''Haese'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Théo'				, 'Defourny'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Hannes'				, 'Delcroix'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Laurent'			, 'Depoitre'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Timothy'			, 'Derijck'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Rémy'				, 'Descamps'			, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Olivier'			, 'Deschacht'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Anthony'			, 'Descotte'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Cyriel'				, 'Dessers'				, @Nigeria		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Dorian'				, 'Dessoleil'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Landry'				, 'Dimata'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Gilles'				, 'Dewaele'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Marvin'				, 'Dewaele'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Modou'				, 'Diagne'				, @Senegal		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Christophe'			, 'Diandy'				, @Senegal		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Guillaume'			, 'Dietsch'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Babacar'			, 'Dione'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Rayan'				, 'Djedje'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Francecsco'			, 'D''Onofrio'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Joren'				, 'Dom'					, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jean-Luc'			, 'Dompe'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Luete Ava'			, 'Dongo'				, @CongoDem		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Niklas'				, 'Dorsch'				, @Germany		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Denis '				, 'Drăguș'				, @Romania		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ferdy'				, 'Druijf'				, @Netherlands	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Frédéric'			, 'Duplus'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Chris'				, 'Durkin'				, @USA			, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Noë'				, 'Dusenne'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Pierre'				, 'Dwomoh'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Joseph'				, 'Efford'				, @USA			, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Blessing'			, 'Eleke'				, @Nigeria		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Carlos'				, 'Embalo'				, @GuineaBissau	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
   ('Björn'				, 'Engels'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Gustav'				, 'Engvall'				, @Sweden		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Josh'				, 'Eppiah'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Collins'			, 'Fai'					, @Cameroon		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Mamadou'			, 'Fall'				, @Senegal		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Imad'				, 'Faraj'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jordan'				, 'Faucher'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Wagane'				, 'Faye'				, @Senegal		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Micael'				, 'Felipe'				, @Brazil		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Viktor'				, 'Fischer'				, @Denmark		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jon'				, 'Flanagan'			, @UnitedKingdom, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Nurio'				, 'Fortuna'				, @Angola		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Guillaume'			, 'François'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Frédéric'			, 'Frans'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Michael'			, 'Frey'				, @Switzerland	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Oleksandr'			, 'Filippov'			, @Ukraine		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Brent'				, 'Gabriël'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Timothy'			, 'Galje'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Alexis'				, 'Gamboa'				, @CostaRica	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Zinho'				, 'Gano'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Pol'				, 'García'				, @Spain		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Nicolas'			, 'Gavory'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jérémy'				, 'Gelin'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Wouter'				, 'George'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Pieter'				, 'Gerkens'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ali'				, 'Gholizadeh'			, @Iran			, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jordy'				, 'Gillekens'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Nick'				, 'Gillekens'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jean-François'		, 'Gillet'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Guillaume'			, 'Gillet'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Silas'				, 'Gnaka'				, @IvoryCoast	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Harlem'				, 'Gnohéré'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Merveille'			, 'Goblet'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Bruno'				, 'Godeau'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Petar'				, 'Golubovic'			, @Serbia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Sergio'				, 'Gómez'				, @Spain		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ivan'				, 'Goranov'				, @Bulgaria		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Omar'				, 'Govea'				, @Mexico		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Grégory'			, 'Grisez'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Lillo'				, 'Guarneri'			, @Italy		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('El Hadji'			, 'Gueye'				, @Senegal		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Makhtar'			, 'Gueye'				, @Senegal		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Pape Habib'			, 'Guèye'				, @Senegal		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Sindrit'			, 'Guri'				, @Albania		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Warner'				, 'Hahn'				, @Suriname		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Geoffry'			, 'Hairemans'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Andreas'			, 'Hanche-Olsen'		, @Norway		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Réda'				, 'Halaimia'			, @Algeria		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Faris'				, 'Haroun'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Daichi'				, 'Hayashi'				, @Japan		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Gaëtan'				, 'Hendrickx'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jack'				, 'Hendry'				, @UnitedKingdom, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Laurent'			, 'Henkinet'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Thomas'				, 'Henry'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Tibo'				, 'Herbots'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jonathan'			, 'Heris'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Daan'				, 'Heymans'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Bryan'				, 'Heynen'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Brendan'			, 'Hines-Ike'			, @USA			, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Andrew'				, 'Hjulsager'			, @Denmark		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Deni'				, 'Hočko'				, @Montenegro	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Wesley'				, 'Hoedt'				, @Netherlands	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Kevin'				, 'Hoggas'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Raphael'			, 'Holzhauser'			, @Austria		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Dino'				, 'Hotic'				, @Bosnia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ethan'				, 'Horvath'				, @USA			, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Patrik'				, 'Hrošovský'			, @Slovakia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('David'				, 'Hubert'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Guillaume'			, 'Hubert'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Cameron'			, 'Humphreys'			, @UnitedKingdom, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Marco'				, 'Ilaimaharitra'		, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Marko'				, 'Ilić'				, @Serbia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Joachim'			, 'Imbrechts'			, @Sweden		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Alexandre'			, 'Ippolito'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Junya'				, 'Ito'					, @Japan		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Tatsuya'			, 'Ito'					, @Japan		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Daniel'				, 'Iversen'				, @Denmark		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Nordin'				, 'Jackers'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Frederik'			, 'Jäkel'				, @Germany		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Adam'				, 'Jakubech'			, @Slovakia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Amadu'				, 'Jalloh'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ablie'				, 'Jallow'				, @Gambia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Laurent'			, 'Jans'				, @Luxembourg	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Wolke'				, 'Janssens'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Vaclav'				, 'Jemelka'				, @CzechRepublic, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Michiel'			, 'Jonckheere'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Denzel'				, 'Jubitana'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Simen'				, 'Juklerød'			, @Norway		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Issa'				, 'Kabore'				, @BurkinaFaso	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Nikos'				, 'Kainourgios'			, @Greece		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Gaël'				, 'Kakudji'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Marco'				, 'Kana'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ismaël'				, 'Kandouss'			, @Morocco		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Onur'				, 'Kaya'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Edo'				, 'Kayembe'				, @CongoDem		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Joris'				, 'Kayembe'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Franck'				, 'Kanouté'				, @Senegal		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Samy'				, 'Kehli'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Aboubakar'			, 'Keita'				, @IvoryCoast	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Sibiry'				, 'Keita'				, @Mali			, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Amine'				, 'Khammas'				, @Morocco		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Gérald'				, 'Kilota'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('João'				, 'Klauss'				, @Brazil		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Tim'				, 'Kleindienst'			, @Germany		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Menno'				, 'Koch'				, @Netherlands	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Hervé'				, 'Koffi'				, @BurkinaFaso	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Aboubakary'			, 'Koita'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Mory'				, 'Konaté'				, @Guinea		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Mamadou'			, 'Koné'				, @IvoryCoast	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Andi'				, 'Koshi'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Odilon'				, 'Kossounou'			, @IvoryCoast	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Sascha'				, 'Kotysch'				, @Germany		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Christian'			, 'Kouamé'				, @IvoryCoast	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Eboue'				, 'Kouassi'				, @IvoryCoast	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Michael'			, 'Krmenčík'			, @CzechRepublic, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Sven'				, 'Kums'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Marko'				, 'Kvasina'				, @Austria		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Sami'				, 'Lahssaini'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Konstantinos'		, 'Laifis'				, @Cyprus		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Boris'				, 'Lambert'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Didier'				, 'Lamkel Ze'			, @Cameroon		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Senne'				, 'Lammens'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Noa'				, 'Lang'				, @Netherlands	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Loïc'				, 'Lapoussin'			, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Siebren'			, 'Lathouwers'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Dragan'				, 'Lausberg'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Kemar'				, 'Lawrence'			, @Jamaica		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Antoine'			, 'Lejoly'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Darko'				, 'Lemajić'				, @Serbia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Christophe'			, 'Lepoint'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Maxime'				, 'Lestienne'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Serge'				, 'Leuko'				, @Cameroon		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Marcel'				, 'Lewis'				, @UnitedKingdom, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Tobe'				, 'Leysen'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Bryan'				, 'Limbombe'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Stallone'			, 'Limbombe'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Perdo'				, 'Lubamba'				, @Angola		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jhonny'				, 'Lucas'				, @Brazil		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jhon'				, 'Lucumi'				, @Colombia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Hakim'				, 'Luqman'				, @Malaysia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jordan'				, 'Lukaku'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Senne'				, 'Lynen'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Mathieu'			, 'Maertens'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Tyreek'				, 'Magee'				, @Jamaica		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Gary'				, 'Magnée'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Yevhen'				, 'Makarenko'			, @Ukraine		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Georges'			, 'Mandjeck'			, @Cameroon		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Kristiyan'			, 'Malinov'				, @Bulgaria		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Sulayman'			, 'Marreh'				, @Gambia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Clinton'			, 'Mata'				, @Angola		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jean Harisson'		, 'Marcelin'			, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Damien'				, 'Marcq'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Francois'			, 'Marquet'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Davor'				, 'Matijaš'				, @Croatia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Keres'				, 'Masangu'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Hamza'				, 'Massoudi'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ko'					, 'Matsubara'			, @Japan		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Youssef'			, 'Maziz'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Dylan'				, 'Mbayo'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Guy'				, 'Mbenza Kamboleke'	, @CongoRep		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Dieumerci'			, 'Mbokani'				, @CongoDem		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ayrton'				, 'Mboko'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ilombé'				, 'Mboyo'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Cameron'			, 'McGeehan'			, @UnitedKingdom, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Brandon'			, 'Mechele'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Xavier'				, 'Mercier'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jenthe'				, 'Mertens'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Senna'				, 'Miangue'				, @CongoRep		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Matt'				, 'Miazga'				, @USA			, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Simon'				, 'Mignolet'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Maxime'				, 'Mignon'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Georges '			, 'Mikautadze'			, @Georgia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Antonio'			, 'Milic'				, @Croatia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Alejandro'			, 'Millàn'				, @Spain		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Kaoru'				, 'Mitoma'				, @Japan		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Matej'				, 'Mitrovic'			, @Croatia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Koji'				, 'Miyoshi'				, @Japan		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Samy'				, 'Mmaee'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Dimitri'			, 'Mohamed'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Milad'				, 'Mohammadi'			, @Iran			, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ryota'				, 'Morioka'				, @Japan		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Anthony'			, 'Moris'				, @Luxembourg	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Marius'				, 'Mouandilmadji'		, @Chad			, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Kerim'				, 'Mrabti'				, @Sweden		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Paul'				, 'Mukairu'				, @Nigeria		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jackson'			, 'Muleka'				, @CongoDem		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Daniel'				, 'Muñoz'				, @Colombia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Amir'				, 'Murillo'				, @Panama		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Anthony'			, 'Musaba'				, @Netherlands	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Knowledge'			, 'Musona'				, @Zimbabwe		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Bohdan'				, 'Mykhaylychenko'		, @Ukraine		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Olivier'			, 'Myny'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Konan'				, 'N''Dri'				, @IvoryCoast	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Darly'				, 'N''Landu'			, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Yahya'				, 'Nadrani'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Radja'				, 'Nainggolan'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Keito'				, 'Nakamura'			, @Japan		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Duckens'			, 'Nazon'				, @Haiti		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Theo'				, 'Ndicka'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Michael'			, 'Ngadeu'				, @Cameroon		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Pierre-Yves'		, 'Ngawa'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Julien'				, 'Ngoy'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Anderson'			, 'Niangbo'				, @IvoryCoast	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Shamar'				, 'Nicholson'			, @Jamaica		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Casper'				, 'Nielsen'				, @Denmark		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Bart'				, 'Nieuwkoop'			, @Netherlands	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ken'				, 'Nkuba'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Lukas'				, 'Nmecha'				, @Germany		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Marius'				, 'Noubissi'			, @Cameroon		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Bruny'				, 'Nsimba'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Stanley'			, 'Nsoki'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Isaac'				, 'Nuhu'				, @Ghana		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Abdul Manaf'		, 'Nurudeen'			, @Ghana		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jonah'				, 'Oasbutey'			, @Ghana		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Eric'				, 'Ocansey'				, @Ghana		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Vadis'				, 'Odjidja-Ofoe'		, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('David'				, 'Okereke'				, @Nigeria		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Fabrice'			, 'Olinga'				, @Cameroon		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Johanna'			, 'Omolo'				, @Kenya		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Junior'				, 'Onana'				, @Cameroon		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Paul'				, 'Onuachu'				, @Nigeria		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Daniel'				, 'Opare'				, @Ghana		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Luca'				, 'Oyen'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Elisha'				, 'Owusu'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Cenk'				, 'Özkacar'				, @Turkey		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Joseph'				, 'Paintsil'			, @Ghana		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Lorenzo'			, 'Paolucci'			, @Italy		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Mathéo'				, 'Parmentier'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Evangelos'			, 'Patoulidis'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Damjan'				, 'Pavlovic'			, @Serbia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Stef'				, 'Peeters'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Nicolas'			, 'Penneteau'			, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Nikola'				, 'Pejčić'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jérémy'				, 'Perbet'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Tibo'				, 'Persyn'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Thibaut'			, 'Peyre'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Theo'				, 'Pierrot'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Tom'				, 'Pietermaat'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Lucas'				, 'Pirard'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Júnior'				, 'Pius'				, @Nigeria		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ihor'				, 'Plastun'				, @Ukraine		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ewoud'				, 'Pletinckx'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Morgan'				, 'Poaty'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Boris'				, 'Popovic'				, @Serbia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Virgiliu'			, 'Postolachi'			, @Moldova		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Benoît'				, 'Poulain'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Small'				, 'Prevljak'			, @Bosnia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Denis'				, 'Prychynenko'			, @Germany		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Robbe'				, 'Quirynen'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Toon'				, 'Raemaekers'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Benito'				, 'Raman'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Nicolas'			, 'Raskin'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Serge-Philippe'		, 'Raux-Yao'			, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Oregan'				, 'Ravet'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Lior'				, 'Refaelov'			, @Israel		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Rocco'				, 'Reitz'				, @Germany		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Tom'				, 'Reyners'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Kaveh'				, 'Rezaei'				, @Iran			, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Lucas'				, 'Ribeiro Costa'		, @Brazil		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Federico'			, 'Ricca'				, @Uruguay		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Mats'				, 'Rits'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ivo'				, 'Rodrigues'			, @Portugal		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Davy'				, 'Roef'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Rafael'				, 'Romo'				, @Venezuela	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Tom'				, 'Roufosse'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Lucas'				, 'Rougeaux'			, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Waldo'				, 'Rubio'				, @Spain		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Abdelhafid'			, 'Sabri'				, @Morocco		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Enes'				, 'Saglik'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Amadou'				, 'Sagna'				, @Senegal		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Trent'				, 'Sainsbury'			, @Australia	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Fashion Junior'		, 'Sakala'				, @Zambia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Albert'				, 'Sambi Lokonga'		, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Mansoni'			, 'Sambu'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Matisse'			, 'Samoise'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ibrahima'			, 'Sankhon'				, @Guinea		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ali'				, 'Sanogo'				, @IvoryCoast	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ryan'				, 'Sanusi'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Abdoulie'			, 'Sanyang'				, @Gambia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Killian'			, 'Sardella'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jordy'				, 'Schelfhout'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Daniel'				, 'Schmidt'				, @Japan		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Rob'				, 'Schoofs'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Brendan'			, 'Schoonbaert'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jur'				, 'Schryvers'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Siebe'				, 'Schrijvers'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Kenneth'			, 'Schuermans'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Abdoulaye'			, 'Seck'				, @Senegal		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ibrahima'			, 'Seck'				, @Senegal		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Faïz'				, 'Selemani'			, @Comoros		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Lee'				, 'Seung-Woo'			, @SouthKorea	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Eden'				, 'Shamir'				, @Israel		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Levan'				, 'Shengelia'			, @Georgia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Nick'				, 'Shinton'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Maryan'				, 'Shved'				, @Ukraine		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Elias'				, 'Sierra'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Aron'				, 'Sigurdarson'			, @Iceland		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Matias'				, 'Silvestre'			, @Argentina	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('William'			, 'Simba'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Danel'				, 'Sinani'				, @Luxembourg	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Abdoulaye'			, 'Sissako'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Moussa'				, 'Sissako'				, @Mali			, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Sambou'				, 'Sissoko'				, @Mali			, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Melvin'				, 'Sitti'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ari'				, 'Skulason'			, @Iceland		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Eduard'				, 'Sobol'				, @Ukraine		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Mikael'				, 'Soisalo'				, @Finland		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Thibo'				, 'Somers'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Matthew'			, 'Sorinola'			, @UnitedKingdom, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Issa'				, 'Soumaré'				, @Senegal		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Abderahmane'		, 'Soussi'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Kamal'				, 'Sowah'				, @Ghana		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Emmanuel'			, 'Sowah Adjel'			, @Ghana		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Bassem'				, 'Srarfi'				, @Tunisia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Warleson'			, 'Steillon Oliveira'	, @Brazil		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Kenny'				, 'Steppe'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jovan'				, 'Stojanović'			, @Serbia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Nikola'				, 'Storm'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Din'				, 'Sula'				, @Albania		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Musashi'			, 'Suzuki'				, @Japan		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Yuma'				, 'Suzuki'				, @Japan		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Eddy'				, 'Sylvestre'			, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Serge'				, 'Tabekou'				, @Cameroon		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ilias'				, 'Takidine'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Mousa'				, 'Tamari'				, @Jordan		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Anton'				, 'Tanghe'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Abdoul Fessal'		, 'Tapsoba'				, @BurkinaFaso	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jérémy'				, 'Taravel'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jorge'				, 'Teixeira'			, @Portugal		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Teddy'				, 'Teuma'				, @Malta		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Kawin '				, 'Thamsatchanan'		, @Thailand		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Isaac'				, 'Thelin'				, @Sweden		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Lukasz'				, 'Teodorczyk'			, @Poland		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Arthur'				, 'Theate'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Mamadou'			, 'Thiam'				, @Senegal		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Yannick'			, 'Thoelen'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Kristian'			, 'Thorstvedt'			, @Norway		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Tarik'				, 'Tissoudali'			, @Netherlands	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('William'			, 'Togui'				, @IvoryCoast	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Bastien'			, 'Toma'				, @Switzerland	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Adrien'				, 'Trebel'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Derrick'			, 'Tshimanga'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Milan'				, 'Tucic'				, @Slovenia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Iké'				, 'Ugbo'				, @UnitedKingdom, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Naomichi'			, 'Ueda'				, @Japan		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Deniz'				, 'Undav'				, @Germany		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jere'				, 'Uronen'				, @Finland		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Georgios'			, 'Vagiannidis'			, @Greece		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jules'				, 'Van Cleemput'		, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Hendrik'			, 'Van Crombrugge'		, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Joachim'			, 'Van Damme'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Miguel'				, 'Van Damme'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Vladimir'			, 'Van De Wiel - Novinchanova'	, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jan'				, 'Van Den Bergh'		, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Yani'				, 'Van Den Bossche'		, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Dario'				, 'Van Den Buijs'		, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Bas'				, 'Van Den Eynden'		, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Thomas'				, 'Van Den Keybus'		, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ignace'				, 'Van Der Brempt'		, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Hannes'				, 'Van Der Bruggen'		, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Siebe'				, 'Van Der Heyden'		, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Stan'				, 'Van Dessel'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Benjamin'			, 'Van Durmen'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jannes'				, 'Van Hecke'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Tom'				, 'Van Hyfte'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Derrick'			, 'Van Luckassen'		, @Netherlands	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Hans'				, 'Vanaken'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Anthony'			, 'Vanden Borre'		, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Kevin'				, 'Vandendriessche'		, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Maarten'			, 'Vandevoordt'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Mike'				, 'Vanhamel'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Zinho'				, 'Vanheusden'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Wim'				, 'Vanmarsenille'		, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Charles'			, 'Vanhoutte'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jorben'				, 'Vanhulle'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jordi'				, 'Vanlerberghe'		, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Dante'				, 'Vanzeir'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Vaso'				, 'Vasic'				, @Serbia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Victor'				, 'Vázquez'				, @Spain		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Daan'				, 'Vekemans'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Dimitar'			, 'Velkovski'			, @Bulgaria		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Rik'				, 'Vercauteren'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Yari'				, 'Verschaeren'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Birger'				, 'Verstraete'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Louis'				, 'Verstraete'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Matthias'			, 'Verreth'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Souza'				, 'Vinícius'			, @Brazil		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Miguel'				, 'Vieira'				, @Portugal		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Michel'				, 'Vlap'				, @Netherlands	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Thibault'			, 'Vlietinck'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Siemen'				, 'Voet'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ruud'				, 'Vormer'				, @Netherlands	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Yan'				, 'Vorogovskiy'			, @Kazakhstan	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Jelle'				, 'Vossen'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Aster'				, 'Vranckx'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ognjen'				, 'Vranješ'				, @Bosnia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Mathéo'				, 'Vroman'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Andrija'			, 'Vukčević'			, @Montenegro	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Aleksandar'			, 'Vukotić'				, @Serbia		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Danny'				, 'Vukovic'				, @Australia	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Sandy'				, 'Walsh'				, @Netherlands	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Timon'				, 'Wellenreuther'		, @Germany		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Maxime'				, 'Wenssens'			, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Victor'				, 'Wernersson'			, @Sweden		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Andreas'			, 'Wiegel'				, @Germany		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Steeven'			, 'Willems'				, @France		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Dries'				, 'Wouters'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Dries'				, 'Wuytens'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Bruno'				, 'Xadas'				, @Portugal		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Roman'				, 'Yaremchuk'			, @Ukraine		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Gjoko'				, 'Zajkov'				, @Macedonia	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Anass'				, 'Zaroury'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Agim'				, 'Zeka'				, @Albania		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Ilyes'				, 'Ziani'				, @Belgium		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Joshua'				, 'Zirkzee'				, @Netherlands	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Adem'				, 'Zorgane'				, @Algeria		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  ('Peter'				, 'Žulj'				, @Austria		, GETDATE(), 'Seed', GETDATE(), 'Seed')
