DECLARE 
	@CurrentSeason BIGINT = (SELECT MAX(Id) FROM Stats.Seasons),
	@Anderlecht BIGINT =	(SELECT Id FROM Stats.Teams WHERE [Name] like '%RSC Anderlecht%'),
	@Antwerp BIGINT =		(SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Antwerp FC%'),
	@Beerschot BIGINT =		(SELECT Id FROM Stats.Teams WHERE [Name] like '%Beerschot VA%'),
	@CercleBrugge BIGINT =	(SELECT Id FROM Stats.Teams WHERE [Name] like '%Cercle Brugge%'),
	@ClubBrugge BIGINT =	(SELECT Id FROM Stats.Teams WHERE [Name] like '%Club Brugge%'),
	@Charleroi BIGINT =		(SELECT Id FROM Stats.Teams WHERE [Name] like '%Royal Charleroi Sporting Club%'),
	@Eupen BIGINT =			(SELECT Id FROM Stats.Teams WHERE [Name] like '%KAS Eupen%'),
	@Genk BIGINT =			(SELECT Id FROM Stats.Teams WHERE [Name] like '%KRC Genk%'),
	@Gent BIGINT =			(SELECT Id FROM Stats.Teams WHERE [Name] like '%KAA Gent%'),
	@Mechelen BIGINT =		(SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Mechelen%'),
	@Kortrijk BIGINT =		(SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Kortrijk%'),
	@OHL BIGINT =			(SELECT Id FROM Stats.Teams WHERE [Name] like '%Oud-Heverlee Leuven%'),
	@Oostende BIGINT =		(SELECT Id FROM Stats.Teams WHERE [Name] like '%KV Oostende%'),
	@Seraing BIGINT =		(SELECT Id FROM Stats.Teams WHERE [Name] like '%RFC Seraing%'),
	@StandardLuik BIGINT =	(SELECT Id FROM Stats.Teams WHERE [Name] like '%Standard Luik%'),
	@STVV BIGINT =			(SELECT Id FROM Stats.Teams WHERE [Name] like '%Sint-Truidense VV%'),
	@ZulteWaregem BIGINT =	(SELECT Id FROM Stats.Teams WHERE [Name] like '%Zulte Waregem%'),
	@Union BIGINT =			(SELECT Id FROM Stats.Teams WHERE [Name] like '%Union%'),

	@Agbadou BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Emmanuel%'		AND [LastName] like '%Agbadou%'),
	@Amade BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Alfons%'		AND [LastName] like '%Amade%'),
	@Amallah BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Selim%'		AND [LastName] like '%Amallah%'),
	@Amani BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Lazare%'		AND [LastName] like '%Amani%'),
	@Ambrose BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Thierry%'		AND [LastName] like '%Ambrose%'),
	@Amuzu BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Francis%'		AND [LastName] like '%Amuzu%'),
	@Balanta BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Éder%'			AND [LastName] like '%Balanta%'),
	@Balongo BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Nelson%'		AND [LastName] like '%Balongo%'),
	@Bätzner BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Nick%'			AND [LastName] like '%Bätzner%'),
	@Beck BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Andreas%'		AND [LastName] like '%Beck%'),
	@Bedia BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Chris%'		AND [LastName] like '%Bedia%'),
	@Benson BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Manuel%'		AND [LastName] like '%Benson%'),
	@Bezus BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Roman%'		AND [LastName] like '%Bezus%'),
	@Bongonda BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Théo%'			AND [LastName] like '%Bongonda%'),
	@Brüls BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Christian%'	AND [LastName] like '%Brüls%'),
	@Bruno BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Gianni%'		AND [LastName] like '%Bruno%'),
	@Capon BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Brecht%'		AND [LastName] like '%Capon%'),
	@CastroMontes BIGINT =	(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Alessio%'		AND [LastName] like '%Castro-Montes%'),
	@Chevalier BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Teddy%'		AND [LastName] like '%Chevalier%'),
	@Cools BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Jens%'			AND [LastName] like '%Cools%'),
	@Cuypers BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Hugo%'			AND [LastName] like '%Cuypers%'),
	@Dietsch BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Guillaume%'	AND [LastName] like '%Dietsch%'),
	@DeBock BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Laurens%'		AND [LastName] like '%De Bock%'),
	@DeKetelaere BIGINT =	(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Charles%'		AND [LastName] like '%De Ketelaere%'),
	@DeLaet BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Ritchie%'		AND [LastName] like '%De Laet%'),
	@Deman BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Olivier%'		AND [LastName] like '%Deman%'),
	@Depoitre BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Laurent%'		AND [LastName] like '%Depoitre%'),
	@DeRidder BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Steve%'		AND [LastName] like '%De Ridder%'),
	@ADeSart BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Alexis%'		AND [LastName] like '%De Sart%'),
	@JDeSart BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Julien%'		AND [LastName] like '%De Sart%'),
	@DHaene BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Kristof%'		AND [LastName] like '%D''Haene%'),
	@Dom BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Joren%'		AND [LastName] like '%Dom%'),
	@Dost BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Bas%'			AND [LastName] like '%Dost%'),
	@Drăguș BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Denis%'		AND [LastName] like '%Drăguș%'),
	@Druijf BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Ferdy%'		AND [LastName] like '%Druijf%'),
	@Embalo BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Carlos%'		AND [LastName] like '%Embalo%'),
	@Fall BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Mamadou%'		AND [LastName] like '%Fall%'),
	@Fischer BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Viktor%'		AND [LastName] like '%Fischer%'),
	@Fortuna BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Nurio%'		AND [LastName] like '%Fortuna%'),
	@Frey BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Michael%'		AND [LastName] like '%Frey%'),
	@Gano BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Zinho%'		AND [LastName] like '%Gano%'),
	@Gavory BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Nicolas%'		AND [LastName] like '%Gavory%'),
	@Gerkens BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Pieter%'		AND [LastName] like '%Gerkens%'),
	@Gholizadeh BIGINT =	(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Ali%'			AND [LastName] like '%Gholizadeh%'),
	@Gómez BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Sergio%'		AND [LastName] like '%Gómez%'),
	@Gueye BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Makhtar%'		AND [LastName] like '%Gueye%'),
	@Guèye BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Pape Habib%'	AND [LastName] like '%Guèye%'),
	@HancheOlsen BIGINT =	(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Andreas%'		AND [LastName] like '%Hanche-Olsen%'),
	@Hayashi BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Daichi%'		AND [LastName] like '%Hayashi%'),
	@Henry BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Thomas%'		AND [LastName] like '%Henry%'),
	@Heris BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Jonathan%'		AND [LastName] like '%Heris%'),
	@Heynen BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Bryan%'		AND [LastName] like '%Heynen%'),
	@Hotic BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Dino%'			AND [LastName] like '%Hotic%'),
	@Ito BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Junya%'		AND [LastName] like '%Ito%'),
	@Jäkel BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Frederik%'		AND [LastName] like '%Jäkel%'),
	@Kaya BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Onur%'			AND [LastName] like '%Kaya%'),
	@EKayembe BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Edo%'			AND [LastName] like '%Kayembe%'),
	@JKayembe BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Joris%'		AND [LastName] like '%Kayembe%'),
	@Keita BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Aboubakar%'	AND [LastName] like '%Keita%'),
	@Klauss BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%João%'			AND [LastName] like '%Klauss%'),
	@Konaté BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Mory%'			AND [LastName] like '%Konaté%'),
	@Kouamé BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Christian%'	AND [LastName] like '%Kouamé%'),
	@Kvasina BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Marko%'		AND [LastName] like '%Kvasina%'),
	@Laifis BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Konstantinos%' AND [LastName] like '%Laifis%'),
	@Lambert BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Boris%'		AND [LastName] like '%Lambert%'),
	@Lang BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Noa%'			AND [LastName] like '%Lang%'),
	@Lapoussin BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Loïc%'			AND [LastName] like '%Lapoussin%'),
	@Lemajić BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Darko%'		AND [LastName] like '%Lemajić%'),
	@Lynen BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Senne%'		AND [LastName] like '%Lynen%'),
	@Maertens BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Mathieu%'		AND [LastName] like '%Maertens%'),
	@Mata BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Clinton%'		AND [LastName] like '%Mata%'),
	@Maziz BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Youssef%'		AND [LastName] like '%Maziz%'),
	@Mboyo BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Ilombé%'		AND [LastName] like '%Mboyo%'),
	@Mignolet BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Simon%'		AND [LastName] like '%Mignolet%'),
	@Mikautadze BIGINT =	(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Georges%'		AND [LastName] like '%Mikautadze%'),
	@Millàn BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Alejandro%'	AND [LastName] like '%Millàn%'),
	@Miyoshi BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Koji%'			AND [LastName] like '%Miyoshi%'),
	@Morioka BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Ryota%'		AND [LastName] like '%Morioka%'),
	@Mouandilmadji BIGINT =	(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Marius%'		AND [LastName] like '%Mouandilmadji%'),
	@Mrabti BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Kerim%'		AND [LastName] like '%Mrabti%'),
	@Muleka BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Jackson%'		AND [LastName] like '%Muleka%'),
	@Muñoz BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Daniel%'		AND [LastName] like '%Muñoz%'),
	@Murillo BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Amir%'			AND [LastName] like '%Murillo%'),
	@NDri BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Konan%'		AND [LastName] like '%N''Dri%'),
	@Ngadeu BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Michael%'		AND [LastName] like '%Ngadeu%'),
	@Nicholson BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Shamar%'		AND [LastName] like '%Nicholson%'),
	@Nielsen BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Casper%'		AND [LastName] like '%Nielsen%'),
	@Ngoy BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Julien%'		AND [LastName] like '%Ngoy%'),
	@Noubissi BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Marius%'		AND [LastName] like '%Noubissi%'),
	@Ocansey BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Eric%'			AND [LastName] like '%Ocansey%'),
	@Onuachu BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Paul%'			AND [LastName] like '%Onuachu%'),
	@Özkacar BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Cenk%'			AND [LastName] like '%Özkacar%'),
	@Paintsil BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Joseph%'		AND [LastName] like '%Paintsil%'),
	@Peeters BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Stef%'			AND [LastName] like '%Peeters%'),
	@Persyn BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Tibo%'			AND [LastName] like '%Persyn%'),
	@Pletinckx BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Ewoud%'		AND [LastName] like '%Pletinckx%'),
	@Popovic BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Boris%'		AND [LastName] like '%Popovic%'),
	@Prevljak BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Small%'		AND [LastName] like '%Prevljak%'),
	@Raman BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Benito%'		AND [LastName] like '%Raman%'),
	@Refaelov BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Lior%'			AND [LastName] like '%Refaelov%'),
	@Reitz BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Rocco%'		AND [LastName] like '%Reitz%'),
	@Rubio BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Waldo%'		AND [LastName] like '%Rubio%'),
	@Sambu BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Mansoni%'		AND [LastName] like '%Sambu%'),
	@Sanyang BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Abdoulie%'		AND [LastName] like '%Sanyang%'),
	@Schrijvers BIGINT =	(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Siebe%'		AND [LastName] like '%Schrijvers%'),
	@Shengelia BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Levan%'		AND [LastName] like '%Shengelia%'),
	@Shved BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Maryan%'		AND [LastName] like '%Shved%'),
	@Selemani BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Faïz%'			AND [LastName] like '%Selemani%'),
	@Sissako BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Abdoulaye%'	AND [LastName] like '%Sissako%'),
	@Sobol BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Eduard%'		AND [LastName] like '%Sobol%'),
	@Sorinola BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Matthew%'		AND [LastName] like '%Sorinola%'),
	@Soumaré BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Issa%'			AND [LastName] like '%Soumaré%'),
	@Storm BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Nikola%'		AND [LastName] like '%Storm%'),
	@Suzuki BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Yuma%'			AND [LastName] like '%Suzuki%'),
	@Tapsoba BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Abdoul%'		AND [LastName] like '%Tapsoba%'),
	@Thelin BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Isaac%'		AND [LastName] like '%Thelin%'),
	@Thorstvedt BIGINT =	(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Kristian%'		AND [LastName] like '%Thorstvedt%'),
	@Tissoudali BIGINT =	(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Tarik%'		AND [LastName] like '%Tissoudali%'),
	@Ugbo BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Iké%'			AND [LastName] like '%Ugbo%'),
	@Undav BIGINT =			(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Deniz%'		AND [LastName] like '%Undav%'),
	@Vanaken BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Hans%'			AND [LastName] like '%Vanaken%'),
	@VanDenBergh BIGINT =	(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Jan%'			AND [LastName] like '%Van Den Bergh%'),
	@Vanhoutte BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Charles%'		AND [LastName] like '%Vanhoutte%'),
	@Vanlerberghe BIGINT =	(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Jordi%'		AND [LastName] like '%Vanlerberghe%'),
	@Vanzeir BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Dante%'		AND [LastName] like '%Vanzeir%'),
	@Verschaeren BIGINT =	(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Yari%'			AND [LastName] like '%Verschaeren%'),
	@Verstraete BIGINT =	(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Birger%'		AND [LastName] like '%Verstraete%'),
	@Vinícius BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Souza%'		AND [LastName] like '%Vinícius%'),
	@Vitinho BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Victor Alexander%'	AND [LastName] like '%da Silva (Vitinho)%'),
	@Vormer BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Ruud%'			AND [LastName] like '%Vormer%'),
	@Vossen BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Jelle%'		AND [LastName] like '%Vossen%'),
	@Zaroury BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Anass%'		AND [LastName] like '%Zaroury%'),
	@Zirkzee BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Joshua%'		AND [LastName] like '%Zirkzee%'),
	@Zorgane BIGINT =		(SELECT Players.Id FROM Stats.Players JOIN [dbo].[Persons] ON Players.[PersonId] = [Persons].Id WHERE [FirstName] like '%Adem%'			AND [LastName] like '%Zorgane%')

INSERT INTO [Stats].[PlayerContracts]
([PlayerId], [TeamId], [ShirtNumber], [StartDateUtc], [EndDateUtc], CreatedUtc, CreatedBy, ModifiedUtc, ModifiedBy)
VALUES
  (@AAitElHadj			,@Anderlecht	, 46, '2019-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@DAlmeida			,@Antwerp		, 61, '2021-07-09', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@NAmpomah			,@Antwerp		, 23, '2020-10-05', '2022-06-30', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@FAmuzu				,@Anderlecht	,  7, '2018-01-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZBakkali			,@Anderlecht	, 99, '2018-07-03', '2021-02-01', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@JBataille			,@Oostende		, 34, '2017-07-01', '2021-07-01', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@JBataille			,@Antwerp		, 34, '2021-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@DBatubinsika		,@Antwerp		, 21, '2017-07-13', '2021-07-23', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ABeiranvand			,@Antwerp		,  1, '2020-07-28', '2021-07-10', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CBenaventeBristol	,@Antwerp		, 24, '2020-10-01', '2021-01-31', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CBenaventeBristol	,@Charleroi		, 24, '2021-02-01', '2021-06-30', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@YBenHamed			,@Antwerp		, 18, '2021-07-06', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@MBenson				,@Genk			, 28, '2017-07-01', '2018-08-18', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@MBenson				,@Genk			, 28, '2019-06-30', '2018-08-18', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@MBenson				,@Antwerp		, 28, '2019-09-02', '2021-01-26', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@MBenson				,@Antwerp		, 28, '2021-06-30', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@MBouchouari			,@Anderlecht	, 34, '2020-12-28', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@FBoya				,@Antwerp		, 15, '2020-07-01', '2021-08-31', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@FBoya				,@ZulteWaregem	, 15, '2021-08-31', '2022-06-30', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@MBundu				,@Anderlecht	, 19, '2020-08-07', '2021-01-26', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@AButa				,@Antwerp		,  5, '2017-08-31', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@JButez				,@Antwerp		,  1, '2020-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ECobbaut			,@Anderlecht	, 22, '2018-07-01', '2021-08-28', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@AColassin			,@Anderlecht	, 53, '2020-07-01', '2021-01-21', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@AColassin			,@Anderlecht	, 53, '2021-06-30', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@JCullen				,@Anderlecht	,  8, '2020-10-05', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@RDeLaet				,@Antwerp		,  2, '2018-01-23', '2018-06-30', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@RDeLaet				,@Antwerp		,  2, '2019-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@HDelcroix			,@Anderlecht	,  3, '2020-06-30', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@NDePauw				,@ZulteWaregem	, 11, '2017-07-01', '2019-07-26', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@NDePauw				,@Antwerp		, 11, '2020-07-24', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@DDessoleil			,@Antwerp		, 24, '2021-08-27', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ODeWolf				,@Eupen			, 26, '2019-07-20', '2021-02-01', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ODeWolf				,@Antwerp		, 26, '2021-02-01', '2021-06-30', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ODeWolf				,@Eupen			, 26, '2021-06-30', '2021-07-05', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ODeWolf				,@Antwerp		, 26, '2021-07-05', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@LDimata				,@Anderlecht	,  9, '2019-07-01', '2021-02-01', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@LDongo				,@Antwerp		, 12, '2020-01-15', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@BEngels				,@ClubBrugge	,  3, '2013-07-01', '2017-08-31', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@BEngels				,@Antwerp		,  3, '2021-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@JGelin				,@Antwerp		, 26, '2020-10-05', '2021-06-30', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@PGerkens			,@Genk			, 16, '2013-07-01', '2016-01-26', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@PGerkens			,@STVV			, 16, '2016-01-26', '2017-01-01', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@PGerkens			,@Anderlecht	, 16, '2017-01-01', '2020-08-12', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@PGerkens			,@Antwerp		, 16, '2020-08-12', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@SGómez				,@Anderlecht	, 17, '2021-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WHahn				,@Anderlecht	, 24, '2021-01-01', '2021-08-04', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WHoedt				,@Anderlecht	,  4, '2021-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@SJuklerød			,@Antwerp		,  6, '2018-07-17', '2021-07-01', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@SJuklerød			,@Genk			,  6, '2021-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@MKana				,@Anderlecht	, 55, '2019-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CKouamé				,@Anderlecht	, 99, '2021-08-21', '2022-06-30', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@DLausberg			,@Antwerp		, 64, '2020-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@KLawrence			,@Anderlecht	, 92, '2020-01-31', '2021-05-07', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@JLukaku				,@Anderlecht	, 94, '2011-12-01', '2013-08-27', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@JLukaku				,@Oostende		, 94, '2013-08-27', '2016-07-22', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@JLukaku				,@Antwerp		, 94, '2020-10-05', '2021-06-30', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@DMatijas			,@Antwerp		, 71, '2020-01-27', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@MMiazga				,@Anderlecht	, 20, '2020-10-03', '2021-06-30', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@AMilic				,@Anderlecht	, 44, '2018-07-01', '2019-08-30', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@AMilic				,@Anderlecht	, 44, '2020-06-30', '2021-01-10', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@KMiyoshi			,@Antwerp		, 19, '2019-08-20', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@PMukairu			,@Anderlecht	, 12, '2020-10-05', '2021-06-30', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@AMurillo			,@Anderlecht	, 62, '2020-01-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@BMykhaylychenko		,@Anderlecht	, 14, '2020-08-03', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@LNmecha				,@Anderlecht	,  7, '2020-08-20', '2021-06-30', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@JPius				,@Antwerp		, 40, '2019-07-01', '2021-02-01', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@JPius				,@STVV			, 40, '2021-02-01', '2022-06-30', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@JPius				,@Antwerp		, 40, '2022-06-30', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@RQuirynen			,@Antwerp		, 17, '2019-07-01', '2020-08-19', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@RQuirynen			,@Antwerp		, 17, '2021-06-30', '2022-01-27', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@BRaman				,@Anderlecht	,  9, '2021-07-15', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@LRefaelov			,@Anderlecht	, 11, '2021-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ASambiLokonga		,@Anderlecht	, 48, '2018-01-01', '2021-07-19', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@KSardella			,@Anderlecht	, 54, '2019-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ASeck				,@Antwerp		,  4, '2018-08-29', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ITakidine			,@Anderlecht	, 27, '2020-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@IThelin				,@Anderlecht	, 24, '2019-06-30', '2020-01-09', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ATrebel				,@Anderlecht	, 25, '2017-01-15', '2022-01-31', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@HVanCrombrugge		,@Anderlecht	, 30, '2019-08-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@AVandenBorre		,@Anderlecht	, 18, '2020-01-17', '2020-07-01', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@DVanLuckassen		,@Anderlecht	, 32, '2019-08-31', '2021-01-10', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@RVercauteren		,@Anderlecht	, 70, '2019-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@YVerschaeren		,@Anderlecht	, 51, '2019-01-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@BVerstraete			,@ClubBrugge	,  6, '2012-07-01', '2014-07-08', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@BVerstraete			,@Kortrijk		,  6, '2015-07-01', '2017-01-17', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@BVerstraete			,@Gent			,  6, '2017-01-17', '2019-07-01', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@BVerstraete			,@Antwerp		,  6, '2020-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@MVlap				,@Anderlecht	, 10, '2019-07-04', '2021-02-01', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OVranješ			,@Anderlecht	, 21, '2018-07-01', '2021-01-25', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@TWellenreuther		,@Anderlecht	,  1, '2020-07-01', '2021-08-18', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@JZirkzee			,@Anderlecht	, 24, '2021-08-03', '2022-06-30', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@PŽulj				,@Anderlecht	, 23, '2019-01-16', '2021-01-11', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  
  (@LVerstraete			,@Antwerp		, 33, '2020-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@SCoopman			,@Antwerp		, 20, '2020-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ADeSart				,@Antwerp		, 25, '2020-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@LRefaelov			,@Antwerp		, 11, '2020-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@FHaroun				,@Antwerp		, 38, '2020-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@RNainggolan			,@Antwerp		,  0, '2020-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@PDwomoh				,@Antwerp		, 80, '2020-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ASoussi				,@Antwerp		, 27, '2020-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@BNsimba				,@Antwerp		, 22, '2020-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@GMbenzaKamboleke	,@Antwerp		,  9, '2020-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@DLamkelZe			,@Antwerp		,  7, '2020-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@IRodrigues			,@Antwerp		,  8, '2020-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@MFrey				,@Antwerp		, 99, '2020-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@VFischer			,@Antwerp		,  7, '2020-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@DMbokani			,@Antwerp		, 70, '2020-07-01', NULL		, GETDATE(), 'Seed', GETDATE(), 'Seed'),

  (@Beerschot, @WBiebauw		, 1 ,  'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, @MVanhamel		, 31,  'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, @ALejoly			, 72,  'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, @JVanDenBergh	, 2 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, @DPrychynenko	, 3 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, @FFrans			, 4 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, @DVanDenBuijs	, 6 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, @PBourdin		, 15, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, @YVorogovskiy	, 24, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, @RHalaimia		, 27, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, @AMboko			, 79, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, @GGrisez			, 89, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, @JDom			, 5 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, @RHolzhauser		, 8 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, @TPietermaat		, 16, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, @RSanusi			, 18, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, @KMasangu		, 19, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, @ICoulibaly		, 28, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, @BEleke			, 7 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, @MNoubissi		, 9 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, @MSuzuki			, 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, @ASanyang		, 22, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@Beerschot, @TTissoudali	, 34, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, @LBrogno			, 92, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, @MFelipe			, 99, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Beerschot, @ISoumaré		, 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),

  (@CercleBrugge, @TDidillon		, 1 ,  'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @SBruzzese		, 89,  'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @MVanDamme		, 16,  'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @MGoblet			, 18,  'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @WSteillonOliveira, 21,  'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @Vitinho			, 2 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @ACorryn			, 25, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @BPopovic			, 5 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @SRauxYao			, 17, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @DBates			, 3 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @JMarcelin		, 24, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @JTaravel			, 4 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @NUeda			, 5 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @DVelkovski		, 19, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @ACassaert		, 32, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @RDecostere		, 8 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @GBiancone		, 41, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @ADeuro			, 6 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @FKanouté			, 98, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @LDaSilvaLopes	, 42, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @JOmolo			, 15, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @KHoggas			, 20, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @CVanhoutte		, 14, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @CDekuyper		, 26, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @AKoshi			, 44, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @TSomers			, 34, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @WRubio			, 7 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@CercleBrugge, @IUgbo			, 9 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @AMusaba			, 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @DHotic			, 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @ODeman			, 23, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@CercleBrugge, @AMillàn			, 29, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),

  (@Charleroi, @NPenneteau		, 1 , 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @JImbrechts		, 14, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @RDescamps		, 40, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @SWillems		, 23, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@Charleroi, @Dessoleil		, 24, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @GZajkov			, 6 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @MDiagne			, 5 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @JKayembe		, 12, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @IGoranov		, 2 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @JVanCleemput	, 4 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @JFlanagan		, 20, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @CDiandy			, 13, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @GHendrickx		, 22, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @MIlaimaharitra	, 26, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @AGholizadeh		, 8 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @MBruno			, 77, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @RMorioka		, 44, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @KNkuba			, 28, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @MFall			, 27, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @ABenchaib		, 34, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @GGillet			, 30, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @LRibeiroCosta	, 19, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @AKeita			, 88, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @SNicholson		, 16, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @ADescotte		, 15, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @KRezaei			, 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @LTeodorczyk		, 91, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @SBerahino		, 38, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @CBedia			, 18, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @AZaroury		, 70, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Charleroi, @AZorgane		, 48, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  
  (@ClubBrugge, @SMignolet			, 88, 'GK'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@ClubBrugge, @EHorvath			, 22, 'GK'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, @NShinton			, 33, 'GK'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, @SLammens			, 91, 'GK'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, @ESobol				, 2 , 'DEF'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, @SNsoki				, 3 , 'DEF'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@ClubBrugge,@OKossounou		, 5 , 'DEF'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, @JHendry			, 5 , 'DEF'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, @MMitrovic			, 15, 'DEF'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, @SDeli				, 17, 'DEF'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, @FRicca				, 18, 'DEF'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, @IVanDerBrempt		, 28, 'DEF'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, @BMechele			, 44, 'DEF'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, @CMata				, 77, 'DEF'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, @EBalanta			, 3 , 'MID'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, @KDiatta			, 11, 'MID'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, @HVanaken			, 20, 'MID'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, @RVormer			, 25, 'MID'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, @MRits				, 26, 'MID'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, @TPersyn			, 16, 'DEF'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, @MDeCuyper			, 55, 'DEF'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, @CDeKetelaere		, 90, 'MID'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, @TVanDenKeybus		, 97, 'ATT'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, @ASagna				, 7 , 'ATT'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, @MKrmenčík			, 9 , 'ATT'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, @NLang				, 10, 'ATT'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@ClubBrugge, @SSchrijvers		, 16, 'ATT'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, @DOkereke			, 21, 'ATT'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, @YBadji				, 27, 'ATT'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, @EDennis			, 42, 'ATT'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ClubBrugge, @BDost				, 29, 'ATT'	, GETDATE(), 'Seed', GETDATE(), 'Seed'),

  (@Eupen, @TRoufosse	, 30, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @ANurudeen	, 33, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @ODeWolf		, 1 , 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @TDefourny	, 31, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @JAmat		, 5 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @SMiangue	, 23, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @BPoulain	, 6 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @ACorreia	, 21, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @SGnaka		, 24, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @GMagnée		, 15, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @BLambert	, 35, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @MKoch		, 3 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @ABeck		, 32, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @ESowahAdjel	, 25, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @EAgbadou	, 22, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @TMagee		, 14, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @MAziz		, 20, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @VVázquez	, 4 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @SKeita		, 13, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @JCools		, 26, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @JHeris		, 28, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @SPeeters	, 8 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @PAkono		, 28, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @EKayembe	, 39, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @KNDri		, 34, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @KMusona		, 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @ABaby		, 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @MKoné		, 77, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @CEmbalo		, 17, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @INuhu		, 29, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @JNgoy		, 7 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Eupen, @SPrevljak	, 9 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  
  (@Genk, @DVukovic		, 1 , 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, @MVandevoordt	, 26, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, @TLeysen		, 40, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, @DWouters		, 4 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk,@GArteaga		, 5 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, @JUronen		, 21, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, @DMuñoz		, 23, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, @JLucumi		, 33, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, @SAdewoye		, 35, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, @CCuesta		, 46, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, @BHeynen		, 8 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, @BToma		, 11, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, @PHrošovský	, 17, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, @ESierra		, 19, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, @MDæhli		, 20, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, @LOyen		, 24, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, @EKouassi		, 38, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, @KThorstvedt	, 42, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@Genk, @PDwomon	, 80, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, @JIto			, 7 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, @CDessers		, 9 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, @TBongonda	, 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, @POnuachu		, 18, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, @BLimbombe	, 22, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, @IUgbo		, 21, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Genk, @JPaintsil	, 28, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),

  (@Gent, @SBolat		, 1 , 'GK ', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @CCoosemans	, 26, 'GK ', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @DRoef		, 33, 'GK ', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @AHancheOlsen	, 21, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @MNgadeu		, 5 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @ACastroMontes, 14, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @MMohammadi	, 15, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @JBotaka		, 17, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @NFortuna		, 25, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @ICissé		, 28, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @BGodeau		, 31, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @IPlastun		, 32, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @DArslanagic	, 36, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @EOwusu		, 6 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @VOdjidjaOfoe	, 8 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @RBezus		, 9 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @GChakvetadze	, 10, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @WGeorge		, 11, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @ADeBruyn		, 12, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @MSamoise		, 19, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @SMarreh		, 22, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @SKums		, 24, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @MParmentier	, 27, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @NDorsch		, 30, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @JDeSart		, 13, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@Gent, @RYaremchuk	, 7 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@Gent, @ANiangbo	, 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @DMbayo		, 18, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @OBukari		, 20, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @LDepoitre	, 29, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @TKleindienst	, 34, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @GBruno		, 19, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @TTissoudali	, 34, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Gent, @DLemajić		, 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),

  (@Kortrijk, @MDeMan			, 16, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, @AJakubech		, 1 , 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, @MIlić			, 31, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, @TDerijck			, 76, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, @KDHaene			, 30, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, @LRougeaux		, 6 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, @TSainsbury		, 5 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, @GDewaele			, 4 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, @BHinesIke		, 3 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, @PGolubovic		, 2 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, @YVanDenBossche	, 41, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, @MJonckheere		, 27, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, @YMakarenko		, 25, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@Kortrijk, @JDeSart		, 23, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, @SSissoko			, 20, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, @CLepoint			, 15, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, @HVanDerBruggen	, 14, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, @EOcansey			, 51, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, @MBadamosi		, 19, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, @PGuèye			, 17, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, @JStojanović		, 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, @FSelemani		, 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, @TChevalier		, 34, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, @HLuqman			, 9 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  -- (@Kortrijk, @IMboyo		, 7 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Kortrijk, @AJalloh			, 22, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  
  (@Mechelen, @GCoucke			, 1 , 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @SBouzian			, 12, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @YThoelen			, 15, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @MWenssens		, 32, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @LBijker			, 3 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @SBateau			, 4 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @SWalsh			, 5 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @RBushiri			, 6 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @SVoet			, 14, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @DDassy			, 22, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @TPeyre			, 23, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @VWernersson		, 26, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @IKabore			, 29, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @JVanlerberghe	, 30, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @GHairemans		, 7 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @OKaya			, 8 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @JVanDamme		, 13, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @RSchoofs			, 16, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @TBoni			, 17, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @LCoveliers		, 18, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @BVanDenEynden	, 37, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @AVranckx			, 40, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @SVinícius		, 33, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @WTogui			, 9 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @IDeCamargo		, 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @NStorm			, 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @KMrabti			, 19, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @GEngvall			, 20, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @NDailly			, 21, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @MShved			, 35, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @FDruijf			, 9 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Mechelen, @HCuypers			, 14, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  
  (@Moucron, @VVasic		, 90, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @LGuarneri		, 88, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @NGillekens	, 34, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @HKoffi		, 16, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @EGueye		, 4 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @MSilvestre	, 26, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @EBocat		, 22, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @SAgouzoul		, 5 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @WSimba		, 40, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @ACiranni		, 13, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @KDabila		, 2 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @RQuirynen		, 18, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @MBakić		, 10, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @DHočko		, 6 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @DMohamed		, 11, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @BVanDurmen	, 30, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @FOlinga		, 7 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @ESaglik		, 28, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @JOnana		, 8 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @DNLandu		, 39, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @BXadas		, 23, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @MVroman		, 19, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @AIppolito		, 27, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @BBadibanga	, 29, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @HGnohéré		, 31, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @VPostolachi	, 9 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @BDione		, 17, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @AZeka			, 45, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @CBrym			, 25, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @IFaraj		, 14, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @STabekou		, 70, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @CCapemba		, 15, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Moucron, @NDaCosta		, 20, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),

  (@OHL, @ORavet		, 38,  'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @DIversen		, 21,  'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @RRomo			, 90,  'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @FDuplus		, 19, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @KSchuermans	, 4 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @DTshimanga	, 3 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @SKotysch		, 23, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @PNgawa		, 5 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @JGillekens	, 27, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @TRaemaekers	, 28, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @BBese			, 18, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @VJemelka		, 2 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @CDeNorre		, 24, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @CÖzkacar		, 35, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @DHubert		, 6 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @SKehli		, 17, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @MMaertens		, 33, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @OMyny			, 22, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @KSowah		, 14, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@OHL, @AKeita		, 99, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @XMercier		, 10, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @TVanHyfte		, 8 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @IAsante		, 20, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @TVlietinck	, 11, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @KMalinov		, 29, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @LShengelia	, 19, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @ADeSart		, 25, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @YAguemon		, 7 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @THenry		, 9 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @MTucic		, 30, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @JPerbet		, 43, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @TBorges		, 24, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @SLimbombe		, 12, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @YCroizet		, 77, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @DVekemans		, 32, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @AAllemeersch	, 39, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @JOasbutey		, 45, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @JEppiah		, 26, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @MTamari		, 13, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@OHL, @SSchrijvers	, 16, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  
  (@Oostende, @JSchelfhout		, 94, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, @GHubert			, 28, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, @BCastro			, 99, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, @TNdicka			, 20, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, @ATheate			, 5 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, @JHendry			, 4 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, @FJäkel			, 15, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, @ATanghe			, 33, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, @BCapon			, 27, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, @ASkulason		, 23, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, @MDewaele			, 12, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, @AAmade			, 23, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, @EPatoulidis		, 24, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, @MDArpino			, 6 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, @AHjulsager		, 17, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, @NBätzner			, 34, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@Oostende, @JBataille		, 25, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, @CMcGeehan		, 18, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, @RDHaese			, 29, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, @IBoonen			, 11, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, @KVandendriessche	, 26, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, @FMarquet			, 8 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, @FSakala			, 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, @MThiam			, 19, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, @MKvasina			, 21, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, @SGuri			, 9 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, @MGueye			, 7 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, @JVanhulle		, 73, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Oostende, @TAmbrose			, 68, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),

  (@Seraing, @MMignon		, 22, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Seraing, @GDietsch		, 30, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Seraing, @TGalje		, 51, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Seraing, @BBoulenger	, 24, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Seraing, @WFaye			, 4 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Seraing, @YNadrani		, 20, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Seraing, @TPierrot		, 6 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Seraing, @FDOnofrio		, 37, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Seraing, @GKakudji		, 25, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Seraing, @GKilota		, 8 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Seraing, @ABernier		, 12, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Seraing, @MSambu		, 21, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Seraing, @MPoaty		, 18, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Seraing, @ASabri		, 10, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Seraing, @SLahssaini	, 15, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Seraing, @SBasha		, 13, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Seraing, @AJallow		, 36, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Seraing, @ICissé		, 44, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Seraing, @AAdelBo		, 58, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Seraing, @RDjedje		, 38, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Seraing, @MCachbach		, 17, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Seraing, @YMaziz		, 88, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Seraing, @ASanogo		, 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Seraing, @MMouandilmadji, 7 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Seraing, @GMikautadze	, 9 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),

  (@StandardLuik, @JGillet			, 1 ,  'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @JABodart			, 16,  'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @LHenkinet		, 30,  'GK', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @ZVanheusden		, 3 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @MSissako			, 5 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @NDusenne			, 6 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @CFai				, 21, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @NGavory			, 24, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @LJans			, 27, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @DPavlovic		, 33, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @KLaifis			, 34, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @GCimirot			, 8 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @MCarcelaGonzalez	, 10, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @WBalikwisha		, 11, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @ESylvestre		, 12, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @EShamir			, 15, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @ABoljević		, 18, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @SAmallah			, 19, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @MBokadi			, 20, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @MLestienne		, 22, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @NRaskin			, 26, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @SBastien			, 28, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @JCarcelaGonzalez	, 29, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@StandardLuik, @DCop			, 7 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @JKlauss			, 9 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @JMuleka			, 17, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @ATapsoba			, 23, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @FAvenatti		, 25, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @MBalikwisha		, 32, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@StandardLuik, @DDrăguș			, 7 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),

  
  (@STVV, @KSteppe			, 1 , 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @DSchmidt			, 21, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @WVanmarsenille	, 35, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @KMatsubara		, 2 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @MCaufriez		, 3 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @PGarcía			, 4 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @ISankhon			, 8 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @LCacace			, 13, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @SMmaee			, 20, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @jTeixeira		, 26, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @SLathouwers		, 31, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @JBuatu			, 39, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @GVagiannidis		, 77, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @SColombatto		, 5 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @LSeungWoo		, 10, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @SAsamoah			, 12, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @SVanDessel		, 19, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @MKonaté			, 24, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @CDurkin			, 32, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @JLucas			, 33, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @HMassoudi		, 70, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @CBrüls			, 44, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @RReitz			, 8 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @YSuzuki			, 9 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @OFilippov		, 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@STVV, @KNakamura		, 15, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @SDeRidder		, 16, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @FColidio			, 18, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @WJanssens		, 22, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @TIto				, 23, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @NBalongo			, 30, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @DNazon			, 90, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @IMboyo			, 7 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@STVV, @DHayashi			, 15, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),

  (@Union, @LPirard			, 21, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Union, @KAtheba			, 26, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Union, @THerbots		, 33, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Union, @AMoris			, 49, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Union, @BNieuwkoop		, 2 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Union, @JBager			, 4 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Union, @MSorinola		, 7 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Union, @CBurgess		, 16, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Union, @GFrançois		, 19, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Union, @SVanDerHeyden	, 44, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Union, @IKandouss		, 59, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Union, @CNielsen		, 6 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Union, @LAmani			, 8 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Union, @MLewis			, 10, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Union, @LPaolucci		, 11, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Union, @TTeuma			, 17, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Union, @SLynen			, 20, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Union, @IZiani			, 24, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Union, @DMarcq			, 25, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Union, @DUndav			, 9 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Union, @DVanzeir		, 13, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Union, @PLubamba		, 22, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Union, @ASigurdarson	, 23, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Union, @FAvenatti		, 90, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@Union, @LLapoussin		, 94, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),

  (@WaaslandBeveren, @NJackers			, 1 , 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @LPirard			, 21, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @BGabriël			, 44, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @VVanDeWiel		, 2 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @BSchoonbaert		, 3 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @FBastians			, 5 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @AWiegel			, 7 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @DWuytens			, 15, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @AGamboa			, 19, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @AVukčević			, 22, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @SLeuko			, 23, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @AKhammas			, 24, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @AVukotić			, 26, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @JMertens			, 27, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @MVieira			, 37, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @JSchryvers		, 52, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @GMandjeck			, 4 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @LBertone			, 6 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @DBizimana			, 8 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @DJubitana			, 14, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @DHeymans			, 18, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @NPejčić			, 20, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @MSitti			, 28, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @MVerreth			, 29, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @MDeMey			, 88, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @JFaucher			, 9 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @DSinani			, 10, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @JEfford			, 11, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @AAlbanese			, 12, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @AKoita			, 17, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @TReyners			, 77, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@WaaslandBeveren, @DSula				, 98, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  -- (@WaaslandBeveren, @MFrey			, 99, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed')

  (@ZulteWaregem, @SBossut		, 1 , 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, @LBostyn		, 25, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, @EBansen		, 44, 'GK' , GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, @WBianda		, 2 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@ZulteWaregem, @ODeschacht	, 3 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, @DOpare		, 4 , 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, @EPletinckx	, 24, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, @LDeBock		, 27, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, @AAbdallah	, 31, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, @CHumphreys	, 33, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, @NKainourgios	, 43, 'DEF', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, @DMarcq		, 5 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, @ASissako		, 6 , 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, @OGovea		, 10, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, @BSrarfi		, 11, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, @ISeck		, 21, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, @JVanHecke	, 67, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, @MSoisalo		, 71, 'MID', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, @JVossen		, 9 , 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, @TChorý		, 15, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, @JDompe		, 17, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  --(@ZulteWaregem, @GBruno		, 19, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, @MDeSmet		, 29, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed'),
  (@ZulteWaregem, @ZGano		, 93, 'ATT', GETDATE(), 'Seed', GETDATE(), 'Seed')